"""Dedicated post-training observability and analysis product."""

from .composition import create_service
from .fixtures import FixtureRunDataSource
from .models import (
    ChartView,
    ComparisonRow,
    EvaluationRunView,
    EvidenceCompleteness,
    EvidenceRequirement,
    ExecutionTargetContext,
    GenericRunView,
    LocatedRunSummary,
    MetricCatalog,
    MetricSeriesQuery,
    MetricSeriesSet,
    PhaseMetricAggregate,
    RunAlert,
    RunComparison,
    RunDelta,
    RunLocator,
    RuntimePhaseIntervalView,
    RuntimePhaseSegment,
    RuntimePhaseSummary,
    RunView,
    RunViewResponse,
    SemanticSummaryRequest,
    SemanticSummaryResult,
    SourceSummary,
    SummaryChange,
    SummaryValue,
    SystemMetricGroup,
    SystemMetricSummary,
    SystemMetricsView,
    TraceDetail,
    TraceEvaluationView,
    WorkPackageView,
)
from .semantic import (
    DisabledSemanticSummaryProvider,
    FixtureSemanticSummaryProvider,
    OpenAICompatibleSemanticSummaryProvider,
    SemanticAnalysisService,
    SemanticSummaryProvider,
)
from .server import serve
from .service import ObservatoryService, RunViewService
from .settings import ObservatorySettings
from .sources import RunSourceRegistry
from .telemetry import (
    DEFAULT_TELEMETRY_DEFINITIONS,
    DISTILL_TELEMETRY,
    DOMAIN_EVAL_TELEMETRY,
    DPO_TELEMETRY,
    GENERAL_EVAL_TELEMETRY,
    GRPO_TELEMETRY,
    SFT_TELEMETRY,
    ArtifactRoleDefinition,
    ChartDefinition,
    EvidenceRequirementDefinition,
    HealthRuleDefinition,
    JobTelemetryDefinition,
    SummaryFieldDefinition,
    TraceSectionDefinition,
    telemetry_registry,
)

__all__ = [
    "ArtifactRoleDefinition",
    "ChartDefinition",
    "ChartView",
    "ComparisonRow",
    "DEFAULT_TELEMETRY_DEFINITIONS",
    "DISTILL_TELEMETRY",
    "DOMAIN_EVAL_TELEMETRY",
    "DPO_TELEMETRY",
    "DisabledSemanticSummaryProvider",
    "EvidenceCompleteness",
    "EvidenceRequirement",
    "EvidenceRequirementDefinition",
    "EvaluationRunView",
    "ExecutionTargetContext",
    "FixtureRunDataSource",
    "FixtureSemanticSummaryProvider",
    "GENERAL_EVAL_TELEMETRY",
    "GRPO_TELEMETRY",
    "GenericRunView",
    "HealthRuleDefinition",
    "JobTelemetryDefinition",
    "LocatedRunSummary",
    "MetricCatalog",
    "MetricSeriesQuery",
    "MetricSeriesSet",
    "ObservatoryService",
    "ObservatorySettings",
    "OpenAICompatibleSemanticSummaryProvider",
    "RunAlert",
    "RunComparison",
    "RunDelta",
    "RunLocator",
    "RunSourceRegistry",
    "RunView",
    "RunViewResponse",
    "PhaseMetricAggregate",
    "RuntimePhaseIntervalView",
    "RuntimePhaseSegment",
    "RuntimePhaseSummary",
    "RunViewService",
    "SFT_TELEMETRY",
    "SemanticAnalysisService",
    "SemanticSummaryProvider",
    "SemanticSummaryRequest",
    "SemanticSummaryResult",
    "SourceSummary",
    "SummaryChange",
    "SummaryFieldDefinition",
    "SummaryValue",
    "SystemMetricGroup",
    "SystemMetricSummary",
    "SystemMetricsView",
    "TraceDetail",
    "TraceEvaluationView",
    "TraceSectionDefinition",
    "WorkPackageView",
    "create_service",
    "telemetry_registry",
    "serve",
]
