"""The metric catalog: what every recorded metric means, described once.

Job views (`telemetry.py`) take a metric's label, description, interpretation
and unit from here, and the semantic layer builds its metric measures from the
same entries (short name, entity, default aggregation, job kinds). An entry
without an entity is described but not yet a semantic measure: its points are
tagged per round or per class, and the semantic layer has no tag dimensions.
"""

from __future__ import annotations

from typing import Literal

from posttrain.common import EPISODE_ENDING_DESCRIPTIONS
from pydantic import Field

from .models import MetricHelp, ObservatoryModel

type CatalogEntity = Literal["collection", "update", "run"]

RESOLVED_UPDATE_KINDS = ("train.capo", "train.gdpo", "train.grpo", "train.sampo")
"""Job kinds whose explicit `policy_updates` engines emit resolved-update evidence."""

ACTIVE_SAMPLING_CATALOG_ROUNDS = 32
"""Active-sampling rounds whose per-round metrics are described (max_candidate_batches in practice is 3-10)."""
type CatalogAggregation = Literal["last", "first", "min", "max", "mean", "sum", "count", "stddev"]


class MetricEntry(ObservatoryModel):
    metric: str = Field(min_length=1)
    name: str = Field(min_length=1)
    label: str = Field(min_length=1)
    description: str = Field(min_length=1)
    interpretation: str | None = None
    caveat: str | None = None
    unit: str | None = None
    entity: CatalogEntity | None = None
    aggregation: CatalogAggregation = "mean"
    allowed: tuple[CatalogAggregation, ...] | None = None
    transform: Literal["identity", "one_minus"] = "identity"
    job_kinds: tuple[str, ...] = Field(min_length=1)

    def help(self) -> MetricHelp:
        if self.interpretation is None:
            raise LookupError(f"metric {self.metric!r} has no interpretation for job views")
        return MetricHelp(
            metric=self.metric,
            label=self.label,
            description=self.description,
            interpretation=self.interpretation,
            caveat=self.caveat,
            unit=self.unit,
        )


def _entry(metric: str, name: str, label: str, description: str, **fields: object) -> MetricEntry:
    return MetricEntry.model_validate(
        {"metric": metric, "name": name, "label": label, "description": description, **fields}
    )


METRIC_CATALOG: tuple[MetricEntry, ...] = (
    _entry(
        "train/loss",
        "loss",
        "Training loss",
        "Mean supervised objective on the current optimization batch.",
        interpretation="A sustained decrease means the model is fitting the rendered training targets; compare it with held-out loss before judging generalization.",
        caveat="Masking, packing, batch composition, and sequence length affect its scale.",
        entity="update",
        job_kinds=("train.capo", "train.dpo", "train.gdpo", "train.grpo", "train.sampo", "train.sft"),
    ),
    _entry(
        "train/validation/loss",
        "validation_loss",
        "Validation loss",
        "The same supervised objective measured on the reserved validation split without updating weights.",
        interpretation="A flattening curve suggests diminishing learning benefit; a rise while training loss falls is evidence of overfitting.",
        caveat="Compare only runs using the same split, renderer, masking policy, and maximum sequence length.",
        entity="update",
        job_kinds=("train.dpo", "train.sft"),
    ),
    _entry(
        "train/mean_token_accuracy",
        "token_accuracy",
        "Token accuracy",
        "Share of supervised tokens whose highest-probability prediction matches the target token.",
        interpretation="Higher is better, but use it with loss because it ignores how confident incorrect and correct predictions are.",
        caveat="Only supervised, non-masked tokens should contribute.",
        unit="ratio",
        entity="update",
        job_kinds=("train.dpo", "train.sft"),
    ),
    _entry(
        "train/grad_norm",
        "grad_norm",
        "Gradient norm",
        "Trainer-recorded global magnitude of gradients before the optimizer update.",
        interpretation="Spikes can indicate unstable batches; a persistently tiny value can indicate stalled learning.",
        caveat="The exact norm and whether it is measured before or after clipping depend on the trainer binding.",
        entity="update",
        job_kinds=("train.capo", "train.distill", "train.dpo", "train.gdpo", "train.grpo", "train.sampo", "train.sft"),
    ),
    _entry(
        "train/learning_rate",
        "logged_learning_rate",
        "Learning rate",
        "Optimizer step size selected by the learning-rate schedule at this logical step.",
        interpretation="Read it beside loss and gradient norm to explain warmup, decay, and changes in update behavior.",
        entity="update",
        job_kinds=("train.capo", "train.distill", "train.dpo", "train.gdpo", "train.grpo", "train.sampo", "train.sft"),
    ),
    _entry(
        "train/gradient_clipped",
        "gradient_clipped",
        "Gradient clipped",
        "Whether, or what share of, the current gradient update exceeded the clipping threshold.",
        interpretation="Occasional clipping is protective; frequent clipping suggests the update scale or data batches deserve inspection.",
        caveat="A per-step boolean is displayed as 0% or 100%; aggregated trainers may report a fraction.",
        unit="ratio",
        entity="update",
        job_kinds=("train.dpo", "train.sft"),
    ),
    _entry(
        "train/non_padding_tokens_per_second",
        "tokens_per_second",
        "Non-padding tokens / second",
        "Effective supervised and context tokens processed per second, excluding padding.",
        interpretation="Higher is better for throughput and is more comparable than raw tokens when sequence lengths and padding differ.",
        caveat="Hardware, world size, packing, checkpointing, and measurement window must match for fair comparisons.",
        unit="tokens/s",
        entity="update",
        job_kinds=("train.dpo", "train.sft"),
    ),
    _entry(
        "train/step_time_seconds",
        "update_seconds",
        "Step time",
        "Wall-clock duration of one logical training step.",
        interpretation="Stable or falling values indicate healthy runtime performance; spikes should be correlated with system metrics and checkpoint activity.",
        unit="s",
        entity="update",
        job_kinds=("train.capo", "train.distill", "train.dpo", "train.gdpo", "train.grpo", "train.sampo", "train.sft"),
    ),
    _entry(
        "train/num_tokens",
        "trained_tokens",
        "Processed tokens",
        "Cumulative number of non-padding training tokens reported by the trainer.",
        interpretation="Use it as the denominator for progress and effective throughput rather than comparing optimizer steps alone.",
        caveat="The trainer binding determines whether prompt and completion tokens are both included.",
        unit="tokens",
        entity="update",
        job_kinds=("train.dpo",),
    ),
    _entry(
        "train/data/supervision_token_ratio",
        "supervision_share",
        "Supervision-token ratio",
        "Fraction of rendered non-padding tokens that contribute to the supervised loss.",
        interpretation="Very low values mean most compute is spent on context rather than learning targets.",
        caveat="The expected range depends on the conversation template and assistant-only masking policy.",
        unit="ratio",
        entity="update",
        job_kinds=("train.sft",),
    ),
    _entry(
        "train/data/truncation_rate",
        "data_truncation_rate",
        "Truncated examples",
        "Fraction of rendered examples shortened by the configured maximum sequence length.",
        interpretation="Lower is usually safer; a high rate means targets or important context may be removed.",
        caveat="Inspect which side of the example is truncated before deciding whether the signal is damaged.",
        unit="ratio",
        entity="update",
        job_kinds=("train.sft",),
    ),
    _entry(
        "train/data/max_length_utilization",
        "length_utilization",
        "Max-length utilization",
        "Average rendered prompt plus longer completion length as a fraction of the configured sequence limit.",
        interpretation="High utilization leaves little room for length variation and increases curation failures near the maximum length.",
        unit="ratio",
        entity="update",
        job_kinds=("train.dpo", "train.sft"),
    ),
    _entry(
        "train/rewards/margins",
        "reward_margin",
        "Reward margin",
        "Average chosen-response reward minus rejected-response reward.",
        interpretation="Positive and increasing values indicate the policy is separating preferred responses from rejected ones.",
        entity="update",
        job_kinds=("train.dpo",),
    ),
    _entry(
        "train/rewards/chosen",
        "chosen_reward",
        "Chosen reward",
        "Average implicit reward assigned to preferred responses.",
        interpretation="It should generally stay above rejected reward; its absolute scale is less useful than their margin.",
        entity="update",
        job_kinds=("train.dpo",),
    ),
    _entry(
        "train/rewards/rejected",
        "rejected_reward",
        "Rejected reward",
        "Average implicit reward assigned to non-preferred responses.",
        interpretation="Read it with chosen reward to determine which side is driving the preference margin.",
        entity="update",
        job_kinds=("train.dpo",),
    ),
    _entry(
        "train/rewards/accuracies",
        "preference_accuracy",
        "Preference accuracy",
        "Fraction of pairs for which the chosen response receives the higher implicit reward.",
        interpretation="Higher values mean the learned preference ordering agrees with the dataset more often.",
        unit="ratio",
        entity="update",
        job_kinds=("train.dpo",),
    ),
    _entry(
        "train/logps/chosen",
        "chosen_logps",
        "Chosen log probability",
        "Average sequence log probability the policy assigns to preferred completions.",
        interpretation="An increase means the chosen responses are becoming more likely under the policy; read it with rejected log probability to distinguish positive learning from rejection-only suppression.",
        caveat="Sequence log probability is length-sensitive, so compare runs only when rendering and length distributions match.",
        entity="update",
        job_kinds=("train.dpo",),
    ),
    _entry(
        "train/logps/rejected",
        "rejected_logps",
        "Rejected log probability",
        "Average sequence log probability the policy assigns to rejected completions.",
        interpretation="A decrease means rejected responses are becoming less likely; if chosen log probability also falls, the margin may be widening through broad suppression.",
        caveat="Sequence log probability is length-sensitive, so compare runs only when rendering and length distributions match.",
        entity="update",
        job_kinds=("train.dpo",),
    ),
    _entry(
        "train/logits/chosen",
        "logits_chosen",
        "Chosen mean logit",
        "Average raw model logit on tokens from preferred completions.",
        interpretation="Use it as a low-level diagnostic for changes in chosen-token scores, not as a standalone quality measure.",
        entity="update",
        job_kinds=("train.dpo",),
    ),
    _entry(
        "train/logits/rejected",
        "logits_rejected",
        "Rejected mean logit",
        "Average raw model logit on tokens from rejected completions.",
        interpretation="Compare it with chosen mean logit only as a low-level optimization diagnostic.",
        entity="update",
        job_kinds=("train.dpo",),
    ),
    _entry(
        "train/entropy",
        "dpo_entropy",
        "Token entropy",
        "Average uncertainty of the policy distribution over non-masked completion tokens.",
        interpretation="A sharp fall can indicate the policy is becoming overly confident or collapsing; stable entropy alongside improving preference separation is generally healthier.",
        entity="update",
        job_kinds=("train.dpo",),
    ),
    _entry(
        "train/validation/rewards/margins",
        "validation_reward_margin",
        "Validation reward margin",
        "Average implicit chosen-minus-rejected reward on reserved preference pairs without updating weights.",
        interpretation="A positive margin that improves with training is held-out evidence that preference separation generalizes beyond optimization pairs.",
        entity="update",
        job_kinds=("train.dpo",),
    ),
    _entry(
        "train/validation/rewards/accuracies",
        "validation_preference_accuracy",
        "Validation preference accuracy",
        "Fraction of reserved pairs whose chosen response receives the higher implicit reward.",
        interpretation="Use it with validation margin and loss; saturated training accuracy with weak validation accuracy indicates memorization.",
        unit="ratio",
        entity="update",
        job_kinds=("train.dpo",),
    ),
    _entry(
        "train/validation/rewards/chosen",
        "validation_chosen_reward",
        "Validation chosen reward",
        "Average implicit reward for chosen responses in the reserved preference split.",
        interpretation="Read it with rejected reward to see which side drives held-out separation.",
        entity="update",
        job_kinds=("train.dpo",),
    ),
    _entry(
        "train/validation/rewards/rejected",
        "validation_rejected_reward",
        "Validation rejected reward",
        "Average implicit reward for rejected responses in the reserved preference split.",
        interpretation="Read it with chosen reward to distinguish improved chosen likelihood from rejection-only suppression.",
        entity="update",
        job_kinds=("train.dpo",),
    ),
    _entry(
        "train/validation/logps/chosen",
        "validation_chosen_logps",
        "Validation chosen log probability",
        "Average policy log-probability assigned to chosen completions in reserved pairs.",
        interpretation="It reveals whether held-out chosen responses become more likely under the policy.",
        caveat="Sequence log probability is length-sensitive.",
        entity="update",
        job_kinds=("train.dpo",),
    ),
    _entry(
        "train/validation/logps/rejected",
        "validation_rejected_logps",
        "Validation rejected log probability",
        "Average policy log-probability assigned to rejected completions in reserved pairs.",
        interpretation="Use it with chosen log probability to explain held-out margin changes.",
        caveat="Sequence log probability is length-sensitive.",
        entity="update",
        job_kinds=("train.dpo",),
    ),
    _entry(
        "train/data/preference_pairs",
        "preference_pairs",
        "Preference pairs",
        "Number of rendered chosen-versus-rejected pairs in the training population.",
        interpretation="Very small populations can be memorized quickly, so training accuracy and reward margin should not be read as generalization evidence.",
        entity="update",
        job_kinds=("train.dpo",),
    ),
    _entry(
        "train/data/prompt_tokens_mean",
        "prompt_tokens_mean",
        "Mean prompt tokens",
        "Average rendered prompt length across preference pairs.",
        interpretation="Use it to understand how much of each sequence is shared context and to compare dataset composition across runs.",
        unit="tokens",
        entity="update",
        job_kinds=("train.dpo",),
    ),
    _entry(
        "train/data/chosen_tokens_mean",
        "chosen_tokens_mean",
        "Mean chosen tokens",
        "Average rendered length of preferred completions.",
        interpretation="Compare it with rejected length to detect a preference dataset that systematically favors longer or shorter answers.",
        unit="tokens",
        entity="update",
        job_kinds=("train.dpo",),
    ),
    _entry(
        "train/data/rejected_tokens_mean",
        "rejected_tokens_mean",
        "Mean rejected tokens",
        "Average rendered length of rejected completions.",
        interpretation="Compare it with chosen length because length imbalance can become an unintended preference shortcut.",
        unit="tokens",
        entity="update",
        job_kinds=("train.dpo",),
    ),
    _entry(
        "train/data/prompt_tokens_p95",
        "prompt_tokens_p95",
        "Prompt tokens p95",
        "Ninety-fifth percentile of rendered prompt length across preference pairs.",
        interpretation="A high tail value identifies prompts most likely to constrain batch density or approach the sequence limit.",
        unit="tokens",
        entity="update",
        job_kinds=("train.dpo",),
    ),
    _entry(
        "train/data/chosen_tokens_p95",
        "chosen_tokens_p95",
        "Chosen tokens p95",
        "Ninety-fifth percentile of preferred-completion length.",
        interpretation="Compare it with rejected p95 to detect a length shortcut hidden by similar means.",
        unit="tokens",
        entity="update",
        job_kinds=("train.dpo",),
    ),
    _entry(
        "train/data/rejected_tokens_p95",
        "rejected_tokens_p95",
        "Rejected tokens p95",
        "Ninety-fifth percentile of rejected-completion length.",
        interpretation="Compare it with chosen p95 to detect systematic tail imbalance between alternatives.",
        unit="tokens",
        entity="update",
        job_kinds=("train.dpo",),
    ),
    _entry(
        "train/data/max_length_headroom_min",
        "length_headroom_min",
        "Minimum length headroom",
        "Smallest remaining token capacity between a rendered preference pair and the configured maximum length.",
        interpretation="Low headroom means at least one pair is close to failing rendering when the template or data changes.",
        caveat="Current DPO rendering rejects over-limit pairs instead of truncating them.",
        unit="tokens",
        entity="update",
        job_kinds=("train.dpo",),
    ),
    _entry(
        "train/data/chosen_longer_fraction",
        "chosen_longer_share",
        "Chosen longer than rejected",
        "Fraction of pairs whose preferred completion is longer than its rejected completion.",
        interpretation="Values far from a balanced population may indicate a systematic length preference that the policy can exploit.",
        caveat="Some tasks legitimately prefer concise or detailed answers; interpret this with task intent.",
        unit="ratio",
        entity="update",
        job_kinds=("train.dpo",),
    ),
    _entry(
        "train/data/preference_score_coverage",
        "preference_score_coverage",
        "Source score coverage",
        "Fraction of preference pairs that retain explicit source scores for both alternatives.",
        interpretation="Higher coverage makes it possible to audit how strong or ambiguous the original preference signal was.",
        unit="ratio",
        entity="update",
        job_kinds=("train.dpo",),
    ),
    _entry(
        "train/data/preference_score_margin_mean",
        "preference_score_margin",
        "Mean source score margin",
        "Average source-score difference between chosen and rejected completions for scored pairs.",
        interpretation="Larger margins represent clearer source preferences; very small margins may be noisy or ambiguous.",
        caveat="Only comparable when the same scorer and score scale produced every pair.",
        entity="update",
        job_kinds=("train.dpo",),
    ),
    _entry(
        "train/rl/reward_mean",
        "reward",
        "Mean reward",
        "Mean verifier reward across the sampled rollout group.",
        interpretation="An upward trend suggests policy improvement when the verifier and sampling policy are unchanged.",
        entity="collection",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/reward_std",
        "reward_std",
        "Reward standard deviation",
        "Spread of verifier rewards within sampled rollout groups.",
        interpretation="Some spread supplies a learning signal; collapse near zero can make relative advantages uninformative.",
        entity="collection",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/kl",
        "kl",
        "KL divergence",
        "Recorded divergence between the updated policy and its reference policy.",
        interpretation="Rising KL means the policy is moving farther from the reference; interpret it against reward improvement and the configured penalty.",
        entity="update",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/entropy",
        "entropy",
        "Policy entropy",
        "Uncertainty of the policy distribution over sampled tokens.",
        interpretation="A sharp decline can indicate premature policy collapse; a persistently high value can indicate weak optimization.",
        entity="update",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/clip_fraction",
        "clip_fraction",
        "Clip fraction",
        "Fraction of policy updates constrained by the objective's clipping range.",
        interpretation="High values mean many updates are hitting the trust-region guardrail and may be too aggressive.",
        unit="ratio",
        entity="update",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/clip_fraction_low",
        "clip_fraction_low",
        "Lower clip fraction",
        "Fraction of active policy updates constrained by the lower DAPO clipping bound.",
        interpretation="Read it separately from the upper clip fraction to see which asymmetric trust-region side is binding.",
        unit="ratio",
        entity="update",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/clip_fraction_high",
        "clip_fraction_high",
        "Upper clip fraction",
        "Fraction of active policy updates constrained by the upper DAPO clipping bound.",
        interpretation="A rising upper-side fraction can indicate aggressive positive-advantage updates even when total clipping looks small.",
        unit="ratio",
        entity="update",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/dynamic_sampling_candidate_batches",
        "dynamic_candidate_batches",
        "Dynamic-sampling candidate batches",
        "Number of candidate rollout batches consumed to fill one collection.",
        interpretation="Values near the configured bound indicate the current policy is producing too many reward-constant groups and may exhaust the sampler.",
        entity="collection",
        job_kinds=("train.capo", "train.gdpo", "train.grpo"),
    ),
    _entry(
        "train/rl/dynamic_sampling_retained_fraction",
        "dynamic_retained_share",
        "Dynamic-sampling retained fraction",
        "Fraction of candidate rollout rows retained after filtering for within-group reward variation.",
        interpretation="A low fraction means the effective environment population is being spent on discarded groups rather than learning signal.",
        unit="ratio",
        entity="collection",
        job_kinds=("train.capo", "train.gdpo", "train.grpo"),
    ),
    _entry(
        "train/rl/active_sampling_generation_rounds",
        "generation_rounds",
        "Active-sampling generation rounds",
        "Number of sequential candidate-generation rounds needed to fill one collection.",
        interpretation="More rounds mean the sampler had to replace more reward-constant candidates before it could assemble an informative update.",
        entity="collection",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/active_sampling_retained_fraction",
        "retained_share",
        "Active-sampling retained fraction",
        "Share of generated candidate rows retained after the reward-variation filter.",
        interpretation="A low fraction means the collection required substantial replacement sampling; inspect it with the candidate-row accounting.",
        unit="ratio",
        entity="collection",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/active_sampling_generated_rows",
        "generated_rows",
        "Active-sampling generated rows",
        "Candidate rows actually generated while filling one collection.",
        interpretation="Compare this with retained rows to quantify the rollout work spent on replacement sampling.",
        entity="collection",
        aggregation="sum",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/active_sampling_candidate_groups_reserved",
        "active_sampling_candidate_groups_reserved",
        "Active-sampling candidate rows reserved",
        "Candidate rows reserved by the dataloader for the bounded active-sampling window.",
        interpretation="Reserved rows that remain unused are capacity held in reserve rather than rollout work already performed.",
        entity="collection",
        aggregation="sum",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/active_sampling_candidate_groups_generated",
        "active_sampling_candidate_groups_generated",
        "Active-sampling candidate rows generated",
        "Candidate rows whose rollouts were generated and scored.",
        interpretation="This is the generated candidate population before filtering, not the final optimizer population.",
        entity="collection",
        aggregation="sum",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/active_sampling_candidate_groups_retained",
        "active_sampling_candidate_groups_retained",
        "Active-sampling candidate rows retained",
        "Generated candidate rows kept because their reward group had usable variation.",
        interpretation="This is the population the collection's updates train on after any bounded oversupply is trimmed.",
        entity="collection",
        aggregation="sum",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/active_sampling_candidate_groups_unused",
        "active_sampling_candidate_groups_unused",
        "Active-sampling candidate rows unused",
        "Reserved candidate rows never generated because the target population was already filled.",
        interpretation="A high value is expected when early candidate rounds are productive; it is not a failed rollout count.",
        entity="collection",
        aggregation="sum",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/active_sampling_oversampled_groups",
        "active_sampling_oversampled_groups",
        "Active-sampling oversampled groups",
        "Prompt groups generated beyond the groups each round was missing, from the oversample and oversample_refill settings.",
        interpretation="This is the extra rollout work spent to avoid serial refill rounds; compare it with generation rounds.",
        entity="collection",
        aggregation="sum",
        job_kinds=("train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/active_sampling_discarded_groups",
        "active_sampling_discarded_groups",
        "Active-sampling discarded groups",
        "Prompt groups with reward spread that were generated but dropped because the collection was already full.",
        interpretation="Discarded groups are the part of oversampling that did not reach the collection; they never carry over to a later collection.",
        entity="collection",
        aggregation="sum",
        job_kinds=("train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/curriculum/candidate_groups",
        "candidate_groups",
        "Controller candidate groups",
        "Task groups selected by the curriculum controller for one initial batch or refill round.",
        interpretation="Sum points at the same optimizer step to recover the complete candidate population selected across refills.",
        job_kinds=("train.capo", "train.gdpo", "train.grpo"),
    ),
    _entry(
        "train/rl/curriculum/unique_tasks",
        "unique_tasks",
        "Controller unique tasks",
        "Selected task identities that did not require degraded duplicate fallback.",
        interpretation="Compare the step total with candidate groups to detect selection pressure caused by an exhausted eligible pool.",
        job_kinds=("train.capo", "train.gdpo", "train.grpo"),
    ),
    _entry(
        "train/rl/curriculum/new_tasks",
        "new_tasks",
        "Controller new tasks",
        "Selected task identities without prior controller evidence.",
        interpretation="This measures task discovery inside the selected candidate population, including refill rounds.",
        job_kinds=("train.capo", "train.gdpo", "train.grpo"),
    ),
    _entry(
        "train/rl/curriculum/discovery_reserved",
        "discovery_reserved",
        "Reserved discovery groups",
        "Candidate slots reserved for tasks without prior controller evidence.",
        interpretation="Sum across a step and compare with fulfilled discovery to distinguish policy intent from available inventory.",
        job_kinds=("train.capo", "train.gdpo", "train.grpo"),
    ),
    _entry(
        "train/rl/curriculum/discovery_fulfilled",
        "discovery_fulfilled",
        "Fulfilled discovery groups",
        "Reserved discovery slots filled with previously unseen tasks.",
        interpretation="A persistent gap from the reserved count means the eligible unseen inventory could not satisfy the request.",
        job_kinds=("train.capo", "train.gdpo", "train.grpo"),
    ),
    _entry(
        "train/rl/curriculum/duplicate_fallbacks",
        "duplicate_fallbacks",
        "Duplicate fallback groups",
        "Selections that repeated a task within an optimizer step after the eligible unique inventory was exhausted.",
        interpretation="Zero is the normal state; a positive value records graceful degradation rather than a failed run.",
        job_kinds=("train.capo", "train.gdpo", "train.grpo"),
    ),
    _entry(
        "train/rl/curriculum/refill_round",
        "refill_round",
        "Controller refill round",
        "One-based refill round index, or zero for an initial non-refill selection.",
        interpretation="Use the maximum point at a step to reconstruct how many controller decisions were needed.",
        job_kinds=("train.capo", "train.gdpo", "train.grpo"),
    ),
    _entry(
        "train/rl/curriculum/class_candidate_groups",
        "class_candidate_groups",
        "Candidate groups by class",
        "Selected task groups for one class, identified by the bounded class_id point attribute.",
        interpretation="Sum by optimizer step and class to reconstruct the controller's allocation without scanning event payloads.",
        job_kinds=("train.capo", "train.gdpo", "train.grpo"),
    ),
    _entry(
        "train/rl/group_zero_variance_fraction",
        "zero_spread_share",
        "Zero-variance groups",
        "Fraction of rollout groups whose rewards contain no within-group variation.",
        interpretation="High values mean GRPO cannot rank alternatives inside many groups even when reward varies globally.",
        unit="ratio",
        entity="collection",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/policy_loss",
        "policy_loss",
        "Policy loss",
        "Policy optimization objective after relative advantages and clipping are applied.",
        interpretation="Interpret its trend with reward, entropy, clipping, and gradient norm rather than as a standalone quality score.",
        entity="update",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    # Resolved policy-update evidence (explicit `policy_updates` on the TRL and
    # veRL engines). One point per applied update; the applied and attempt
    # counters are cumulative, so runs aggregate them with max/last, never sum.
    _entry(
        "train/rl/loss",
        "resolved_loss",
        "Resolved objective",
        "Complete resolved objective (policy plus KL terms) evaluated for the applied update, not a native replay carrier.",
        interpretation="Read it with policy and KL loss; a difference from policy loss is the selected KL contribution.",
        caveat="Its scale depends on the declared reductions and selected actions, so compare only runs with the same objective digest.",
        entity="update",
        allowed=("last", "first", "min", "max", "mean", "stddev"),
        job_kinds=RESOLVED_UPDATE_KINDS,
    ),
    _entry(
        "train/rl/kl_loss",
        "kl_loss",
        "KL loss",
        "Weighted KL-regularization term of the resolved objective, over the separately selected KL actions.",
        interpretation="Zero means no KL penalty was selected (beta 0) or the policy still matches its reference.",
        entity="update",
        allowed=("last", "first", "min", "max", "mean", "stddev"),
        job_kinds=RESOLVED_UPDATE_KINDS,
    ),
    _entry(
        "train/rl/applied_optimizer_updates",
        "applied_updates",
        "Applied optimizer updates",
        "Cumulative count of committed optimizer updates at this point, including updates restored from a checkpoint.",
        interpretation="It should rise by exactly one per point; a gap or repeat means a missing or duplicated update report.",
        caveat="Overflow-skipped, all-zero or omitted updates are not applied updates.",
        entity="update",
        aggregation="max",
        allowed=("last", "first", "min", "max", "count"),
        job_kinds=RESOLVED_UPDATE_KINDS,
    ),
    _entry(
        "train/rl/optimizer_attempts",
        "optimizer_attempts",
        "Optimizer attempts",
        "Cumulative count of optimizer attempts, including attempts skipped by FP16 overflow and later retried.",
        interpretation="Attempts above applied updates are skipped steps; the skipped_optimizer_attempts metric computes the difference.",
        entity="update",
        aggregation="max",
        allowed=("last", "first", "min", "max", "count"),
        job_kinds=RESOLVED_UPDATE_KINDS,
    ),
    _entry(
        "train/rl/selected_policy_actions",
        "selected_policy_actions",
        "Selected policy actions",
        "Sampled action tokens carrying policy-loss weight in this applied update.",
        interpretation="Sum across updates for total gradient-bearing action occurrences; a reused population counts each occurrence.",
        caveat="Membership itself lives in immutable update artifacts; this is only the count.",
        entity="update",
        aggregation="sum",
        job_kinds=RESOLVED_UPDATE_KINDS,
    ),
    _entry(
        "train/rl/selected_kl_actions",
        "selected_kl_actions",
        "Selected KL actions",
        "Sampled action tokens carrying KL-regularization weight in this applied update.",
        interpretation="KL support is selected independently of policy support; equal counts mean both cover the same actions.",
        entity="update",
        aggregation="sum",
        job_kinds=RESOLVED_UPDATE_KINDS,
    ),
    _entry(
        "train/rl/advantage_mean",
        "advantage_mean",
        "Mean advantage",
        "Mean prepared advantage over the policy actions of the update.",
        interpretation="Group-relative credit is centred per group, so the population mean is near zero; minibatches of one population need not be.",
        caveat="Resolved engines average over policy-selected actions; the legacy veRL path averages its native advantage rows.",
        entity="update",
        job_kinds=RESOLVED_UPDATE_KINDS,
    ),
    _entry(
        "train/rl/advantage_abs_mean",
        "advantage_abs_mean",
        "Mean absolute advantage",
        "Mean magnitude of prepared advantages over the policy actions of the update.",
        interpretation="Zero means the update carried no policy-gradient signal, whatever the optimizer step did.",
        caveat="Resolved engines average over policy-selected actions; the legacy veRL path averages its native advantage rows.",
        entity="update",
        job_kinds=RESOLVED_UPDATE_KINDS,
    ),
    _entry(
        "train/rl/advantage_std",
        "advantage_std",
        "Advantage spread",
        "Population standard deviation of prepared advantages over the policy actions of the update.",
        interpretation="Low spread with a nonzero mean means the update pushes selected actions in one direction.",
        caveat="Resolved engines average over policy-selected actions; the legacy veRL path averages its native advantage rows.",
        entity="update",
        job_kinds=RESOLVED_UPDATE_KINDS,
    ),
    _entry(
        "train/rl/advantage_nonzero_fraction",
        "advantage_nonzero_share",
        "Actions with nonzero advantage",
        "Share of policy-selected actions in the applied update whose prepared advantage is nonzero.",
        interpretation="Zero means an uninformative update (for example a reward-constant group); one means every selected action carried credit.",
        caveat="The run mean weights updates equally; weight by selected policy actions for an action-level share.",
        unit="ratio",
        entity="update",
        allowed=("last", "first", "min", "max", "mean", "stddev"),
        job_kinds=RESOLVED_UPDATE_KINDS,
    ),
    _entry(
        "train/loss_scale",
        "loss_scale",
        "FP16 loss scale",
        "Dynamic gradient-scaler loss scale after the optimizer step.",
        interpretation="A falling scale records overflow back-off; a rising scale records growth after stable steps.",
        caveat="Only FP16 training with a gradient scaler records it.",
        entity="update",
        aggregation="last",
        allowed=("last", "first", "min", "max"),
        job_kinds=RESOLVED_UPDATE_KINDS,
    ),
    _entry(
        "train/optimizer_step_skipped",
        "optimizer_step_skipped",
        "Optimizer step skipped",
        "Whether the native optimizer skipped this step because the scaled gradients were not finite (1) or applied it (0).",
        interpretation="Sum across updates for the number of skipped steps the native scaler reported.",
        caveat="Only FP16 training with a gradient scaler records it.",
        entity="update",
        aggregation="sum",
        allowed=("sum", "max", "mean", "last", "count"),
        job_kinds=RESOLVED_UPDATE_KINDS,
    ),
    _entry(
        "train/optimizer_steps_skipped",
        "optimizer_steps_skipped_total",
        "Optimizer steps skipped (cumulative)",
        "Cumulative native count of optimizer steps skipped for non-finite scaled gradients.",
        interpretation="Use its maximum for the run total; it never decreases within one uninterrupted run.",
        caveat="Only FP16 training with a gradient scaler records it.",
        entity="update",
        aggregation="max",
        allowed=("last", "first", "min", "max"),
        job_kinds=RESOLVED_UPDATE_KINDS,
    ),
    _entry(
        "train/rl/rollouts_requested",
        "rollouts_requested",
        "Requested rollouts",
        "Number of rollout attempts requested for the logical step.",
        interpretation="Compare it with terminal attempts to distinguish a smaller configured batch from work that never reached a terminal trace.",
        entity="collection",
        job_kinds=("train.capo", "train.gdpo", "train.grpo"),
    ),
    _entry(
        "train/rl/rollouts_attempted",
        "rollouts_attempted",
        "Terminal rollouts",
        "Number of requested rollout attempts that reached a retained terminal trace.",
        interpretation="This is the observed population denominator for completion, failure, truncation, and scoring coverage.",
        entity="collection",
        aggregation="sum",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/rollouts_missing",
        "rollouts_missing",
        "Missing rollout evidence",
        "Requested rollout attempts that did not reach a retained terminal trace.",
        interpretation="This is not a failure count: inspect cancellation and runtime evidence before assigning a cause.",
        entity="collection",
        job_kinds=("train.capo", "train.gdpo", "train.grpo"),
    ),
    _entry(
        "train/rl/rollouts_completed",
        "rollouts_completed",
        "Completed rollouts",
        "Number of rollout attempts that returned a terminal result.",
        interpretation="Compare it with attempted rollouts; a gap means the collection's updates saw less evidence than configured.",
        entity="collection",
        aggregation="sum",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/rollouts_failed",
        "rollouts_failed",
        "Failed rollouts",
        "Number of rollout attempts that ended in an execution or environment error.",
        interpretation="Any non-zero value requires trace-level inspection because failed work can bias the effective batch.",
        entity="collection",
        aggregation="sum",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/rollouts_truncated",
        "rollouts_truncated",
        "Truncated rollouts",
        "Number of completed rollouts stopped by a token, step, or time limit.",
        interpretation="Truncation can hide task completion and bias rewards toward shorter trajectories.",
        entity="collection",
        aggregation="sum",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/rollouts_unscorable",
        "rollouts_unscorable",
        "Unscorable rollouts",
        "Number of returned rollouts without a finite verifier reward.",
        interpretation="Unscorable trajectories cannot contribute a valid relative learning signal and should be treated as evidence loss.",
        entity="collection",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/completion_tokens_mean",
        "completion_tokens_mean",
        "Mean completion tokens",
        "Average generated completion length for the rollout population.",
        interpretation="Length drift can indicate changing task behavior, truncation pressure, or reward exploitation.",
        unit="tokens",
        entity="collection",
        job_kinds=("train.capo", "train.gdpo", "train.grpo"),
    ),
    _entry(
        "train/rl/completion_tokens_max",
        "completion_tokens_max",
        "Maximum completion tokens",
        "Longest generated completion in the observed rollout population.",
        interpretation="Repeated contact with the configured limit suggests generation is capacity constrained.",
        unit="tokens",
        entity="collection",
        job_kinds=("train.capo", "train.gdpo", "train.grpo"),
    ),
    _entry(
        "train/rl/completion_truncation_rate",
        "truncation_rate",
        "Completion truncation rate",
        "Fraction of completions stopped at the configured generation limit.",
        interpretation="A rising rate means reward and completion statistics increasingly describe partial trajectories.",
        unit="ratio",
        entity="collection",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/rollout_tokens_per_second",
        "rollout_tokens_per_second",
        "Rollout tokens per second",
        "Effective completion-token throughput during rollout generation.",
        interpretation="Compare runs only when model, hardware, sequence distribution, and rollout topology are comparable.",
        unit="tokens/s",
        entity="collection",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/sampling_logp_delta_mean",
        "sampling_logp_delta_mean",
        "Mean sampling log-probability delta",
        "Mean difference between rollout-server sampling log-probabilities and actor recomputation.",
        interpretation="Drift away from zero can expose serving-versus-training numerical mismatch or stale policy weights.",
        entity="update",
        job_kinds=("train.capo", "train.gdpo", "train.grpo"),
    ),
    _entry(
        "train/rl/sampling_logp_delta_max",
        "sampling_logp_delta_max",
        "Maximum sampling log-probability delta",
        "Largest observed rollout-versus-actor log-probability difference.",
        interpretation="Outliers can destabilize importance correction even when the mean remains small.",
        entity="update",
        job_kinds=("train.capo", "train.gdpo", "train.grpo"),
    ),
    _entry(
        "train/rl/importance_sampling_ratio_mean",
        "correction_ratio",
        "Mean importance ratio",
        "Mean actor-to-rollout probability ratio used to correct decoupled sampling.",
        interpretation="Values near one indicate close policies; interpret with the min and max because the mean hides tail instability.",
        entity="update",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/importance_sampling_ratio_min",
        "importance_sampling_ratio_min",
        "Minimum importance ratio",
        "Smallest actor-to-rollout probability ratio in the observed batch.",
        interpretation="Very small values identify samples whose rollout probability substantially exceeds the current actor probability.",
        entity="update",
        job_kinds=("train.capo", "train.gdpo", "train.grpo"),
    ),
    _entry(
        "train/rl/importance_sampling_ratio_max",
        "importance_sampling_ratio_max",
        "Maximum importance ratio",
        "Largest actor-to-rollout probability ratio in the observed batch.",
        interpretation="Large tail values can dominate updates unless correction or clipping is active.",
        entity="update",
        job_kinds=("train.capo", "train.gdpo", "train.grpo"),
    ),
    _entry(
        "train/rl/policy_staleness_mean",
        "policy_staleness_mean",
        "Mean policy staleness",
        "Average number of policy versions between trajectory generation and optimization.",
        interpretation="Higher staleness weakens on-policy assumptions and should be read with importance ratios and reward progress.",
        unit="versions",
        entity="collection",
        job_kinds=("train.capo", "train.gdpo", "train.grpo"),
    ),
    _entry(
        "train/rl/policy_staleness_max",
        "policy_staleness_max",
        "Maximum policy staleness",
        "Largest observed policy-version delay for trajectories consumed by the collection.",
        interpretation="A high tail can reveal queue backlog that is hidden by an acceptable mean.",
        unit="versions",
        entity="collection",
        job_kinds=("train.capo", "train.gdpo", "train.grpo"),
    ),
    _entry(
        "train/rl/trajectory_version_span_mean",
        "trajectory_version_span_mean",
        "Mean trajectory version span",
        "Average policy-version span represented within an optimization batch.",
        interpretation="Wide batches mix behavior from different policy states and make update interpretation less direct.",
        unit="versions",
        entity="collection",
        job_kinds=("train.capo", "train.gdpo", "train.grpo"),
    ),
    _entry(
        "train/rl/tool_call_frequency",
        "tool_call_rate",
        "Tool-call frequency",
        "Fraction of rollouts that invoked at least one environment tool.",
        interpretation="A change can represent better task engagement or reward gaming; inspect linked traces to distinguish them.",
        unit="ratio",
        entity="collection",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/tool_failure_frequency",
        "tool_failure_rate",
        "Tool-failure frequency",
        "Fraction of rollouts with at least one failed tool invocation.",
        interpretation="Failures reduce usable evidence and often explain reward degradation or longer trajectories.",
        unit="ratio",
        entity="collection",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/time/rollout_seconds",
        "rollout_seconds",
        "Rollout time",
        "Wall-clock time spent generating trajectories for a logical step.",
        interpretation="Use it with total step time to locate generation-bound runs.",
        unit="s",
        entity="collection",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/time/reward_seconds",
        "reward_seconds",
        "Reward time",
        "Wall-clock time spent evaluating verifier rewards.",
        interpretation="A large share of step time identifies verifier or environment evaluation as the bottleneck.",
        unit="s",
        entity="collection",
        job_kinds=("train.capo", "train.gdpo", "train.grpo"),
    ),
    _entry(
        "train/rl/time/actor_forward_seconds",
        "actor_forward_seconds",
        "Actor forward time",
        "Wall-clock time spent recomputing actor probabilities for sampled trajectories.",
        interpretation="Compare it with actor update time to distinguish scoring cost from backpropagation cost.",
        unit="s",
        entity="update",
        job_kinds=("train.capo", "train.gdpo", "train.grpo"),
    ),
    _entry(
        "train/rl/time/actor_update_seconds",
        "actor_seconds",
        "Actor update time",
        "Wall-clock time spent applying the policy optimization update.",
        interpretation="A rising value with stable token counts can reveal memory pressure or distributed synchronization overhead.",
        unit="s",
        entity="update",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "train/rl/time/weight_sync_seconds",
        "weight_sync_seconds",
        "Weight synchronization time",
        "Wall-clock time spent moving updated policy weights to the rollout runtime.",
        interpretation="This is a direct tax of decoupled serving and should be judged against rollout throughput gains.",
        unit="s",
        entity="collection",
        job_kinds=("train.capo", "train.gdpo", "train.grpo"),
    ),
    _entry(
        "train/rl/time/checkpoint_seconds",
        "checkpoint_seconds",
        "Checkpoint time",
        "Wall-clock time spent writing recovery state.",
        interpretation="Checkpoint spikes are operational overhead, not model-learning regressions.",
        unit="s",
        entity="update",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "serve/backend/speculative_draft_tokens",
        "speculative_draft_tokens",
        "Speculative draft tokens",
        "Number of tokens proposed by the speculative MTP path.",
        interpretation="This is opportunity volume, not acceleration by itself; pair it with accepted tokens and measured throughput.",
        unit="tokens",
        entity="collection",
        job_kinds=("train.capo", "train.gdpo", "train.grpo"),
    ),
    _entry(
        "serve/backend/speculative_accepted_tokens",
        "speculative_accepted_tokens",
        "Accepted speculative tokens",
        "Number of drafted tokens accepted by target-model verification.",
        interpretation="More accepted tokens can reduce target decoding work, but only measured throughput establishes a speedup.",
        unit="tokens",
        entity="collection",
        job_kinds=("train.capo", "train.gdpo", "train.grpo"),
    ),
    _entry(
        "serve/backend/speculative_acceptance_rate",
        "speculative_acceptance",
        "Speculative acceptance rate",
        "Fraction of drafted MTP tokens accepted by target-model verification.",
        interpretation="Acceptance describes draft quality; it does not account for drafting overhead or prove end-to-end acceleration.",
        unit="ratio",
        entity="collection",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "serve/backend/speculative_accepted_length",
        "speculative_accepted_length",
        "Accepted speculative length",
        "Mean accepted speculative-token run length per verification cycle.",
        interpretation="Longer accepted runs usually reduce target decode iterations, subject to drafting and synchronization cost.",
        unit="tokens",
        entity="collection",
        job_kinds=("train.capo", "train.gdpo", "train.grpo"),
    ),
    _entry(
        "serve/backend/kv_cache_capacity_tokens",
        "kv_cache_capacity_tokens",
        "KV-cache token capacity",
        "Runtime-reported token capacity for the selected KV-cache representation.",
        interpretation="Capacity is a configuration outcome and must not be inferred from the selected TurboQuant dtype alone.",
        unit="tokens",
        entity="collection",
        job_kinds=("train.capo", "train.gdpo", "train.grpo"),
    ),
    _entry(
        "serve/backend/kv_cache_peak_usage_ratio",
        "kv_cache_peak",
        "Peak KV-cache usage",
        "Highest observed share of the runtime KV-cache capacity used during the run.",
        interpretation="A high value signals limited headroom; a missing value means quantized-cache qualification is incomplete.",
        unit="ratio",
        entity="collection",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "train/distill/loss",
        "distill_loss",
        "Distillation loss",
        "Student training objective computed from teacher-scored tokens.",
        interpretation="A decrease means the student is better matching the teacher under the configured objective.",
        entity="update",
        job_kinds=("train.distill",),
    ),
    _entry(
        "train/distill/reverse_kl",
        "reverse_kl",
        "Reverse KL",
        "Reverse Kullback-Leibler divergence from student to teacher on scored tokens.",
        interpretation="Lower values indicate closer student alignment to the teacher distribution.",
        entity="update",
        job_kinds=("train.distill",),
    ),
    _entry(
        "train/distill/scored_tokens",
        "scored_tokens",
        "Scored tokens",
        "Number of tokens successfully scored by the teacher and included in distillation.",
        interpretation="Use it to confirm that effective supervision volume grows as expected.",
        entity="update",
        aggregation="sum",
        job_kinds=("train.distill",),
    ),
    _entry(
        "train/distill/teacher_latency_ms",
        "teacher_latency_ms",
        "Teacher latency",
        "Mean time spent obtaining teacher scores for a batch.",
        interpretation="Higher values identify teacher inference as a throughput bottleneck.",
        unit="ms",
        entity="update",
        job_kinds=("train.distill",),
    ),
    _entry(
        "train/distill/teacher_failures",
        "teacher_failures",
        "Teacher failures",
        "Count of teacher-scoring failures excluded from training.",
        interpretation="Any non-zero value means the effective training population is incomplete and should be investigated.",
        entity="update",
        aggregation="sum",
        job_kinds=("train.distill",),
    ),
    _entry(
        "eval/run/rollouts_complete",
        "eval_rollouts_complete",
        "Completed rollouts",
        "Number of evaluation rollouts that reached a terminal result.",
        interpretation="Compare it with the expected population to judge evaluation completeness.",
        entity="run",
        aggregation="sum",
        job_kinds=("eval.domain", "eval.general"),
    ),
    _entry(
        "eval/run/rollouts_failed",
        "eval_rollouts_failed",
        "Failed rollouts",
        "Number of rollouts that ended with an execution or verifier error.",
        interpretation="Non-zero values reduce aggregate coverage and should be inspected at trace level.",
        entity="run",
        aggregation="sum",
        job_kinds=("eval.domain", "eval.general"),
    ),
    _entry(
        "eval/run/model_call_error_rollouts",
        "eval_model_call_error_rollouts",
        "Model-call error rollouts",
        "Number of evaluation attempts containing at least one failed model request.",
        interpretation="These attempts are execution failures, not semantic task failures or valid zero rewards.",
        entity="run",
        aggregation="sum",
        job_kinds=("eval.domain", "eval.general"),
    ),
    _entry(
        "eval/run/model_call_http_400_rollouts",
        "eval_http_400_rollouts",
        "HTTP 400 model-call rollouts",
        "Number of evaluation attempts with a model request rejected as HTTP 400.",
        interpretation="Check the inference request and model context budget before interpreting scores.",
        entity="run",
        aggregation="sum",
        job_kinds=("eval.domain", "eval.general"),
    ),
    _entry(
        "eval/run/context_overflow_rollouts",
        "eval_context_overflow_rollouts",
        "Context-overflow rollouts",
        "Number of attempts whose model request reported maximum-context-length overflow.",
        interpretation="Increase qualified context capacity or bound the per-call output reservation.",
        entity="run",
        aggregation="sum",
        job_kinds=("eval.domain", "eval.general"),
    ),
    _entry(
        "eval/run/rollouts_truncated",
        "eval_rollouts_truncated",
        "Truncated rollouts",
        "Number of rollouts stopped by a token, time, or step limit.",
        interpretation="A high count can bias aggregate scores because tasks did not receive a full attempt.",
        entity="run",
        aggregation="sum",
        job_kinds=("eval.domain", "eval.general"),
    ),
    _entry(
        "eval/trace_sync_complete",
        "eval_trace_sync_complete",
        "Trace synchronization complete",
        "Whether all native evaluation traces have been synchronized into the tracking reader.",
        interpretation="A value of 100% means aggregates can link back to their complete trace population.",
        unit="ratio",
        entity="run",
        aggregation="min",
        job_kinds=("eval.domain", "eval.general"),
    ),
    _entry(
        "eval/trace_sync_schema_mismatch",
        "trace_sync_schema_mismatch",
        "Trace schema mismatch",
        "Whether the producer and tracking client disagreed about a trace-fact dimension.",
        interpretation="Use a compatible immutable runtime before submitting another evaluation.",
        entity="run",
        aggregation="last",
        job_kinds=("eval.domain", "eval.general"),
    ),
    _entry(
        "train/rl/episode_advantage_mean",
        "episode_advantage",
        "Episode advantage",
        "Mean trajectory-level advantage assigned from the complete episode return.",
        interpretation="Centred within each prompt group, so it is zero by construction; read episode credit for its size.",
        entity="collection",
        job_kinds=("train.sampo",),
    ),
    _entry(
        "train/rl/turn_advantage_mean",
        "turn_advantage",
        "Turn advantage",
        "Mean step-aware advantage assigned to sampled assistant turns.",
        interpretation="Centred within each anchor group, so it is zero by construction; read turn credit and its share instead.",
        entity="collection",
        job_kinds=("train.sampo",),
    ),
    _entry(
        "train/rl/episode_advantage_abs_mean",
        "episode_advantage_magnitude",
        "Episode credit",
        "Mean absolute trajectory-level advantage: how strongly whole episodes are ranked within their prompt group.",
        interpretation="Zero means every attempt at a task scored the same, so the collection carries no episode-level signal.",
        entity="collection",
        job_kinds=("train.sampo",),
    ),
    _entry(
        "train/rl/turn_advantage_abs_mean",
        "turn_advantage_magnitude",
        "Turn credit",
        "Mean absolute turn-level advantage: how strongly turns are ranked against other attempts from the same state.",
        interpretation="Compare with episode credit; turn credit near zero means SAMPO is behaving like episode-level GRPO.",
        entity="collection",
        job_kinds=("train.sampo",),
    ),
    _entry(
        "train/rl/turn_credit_share",
        "turn_credit_share",
        "Turn share of credit",
        "Share of each turn's credit (episode advantage plus weighted turn advantage) that comes from the turn level.",
        interpretation="The headline SAMPO signal: 0% is plain episode credit; higher values mean turns are judged on their own consequences.",
        unit="ratio",
        entity="collection",
        job_kinds=("train.sampo",),
    ),
    _entry(
        "train/rl/turn_advantage_informative_fraction",
        "turn_credit_coverage",
        "Turns with turn credit",
        "Fraction of sampled turns whose turn advantage is non-zero, so they were ranked against a comparable attempt.",
        interpretation="Low coverage means most turns had no peer from the same state or all peers earned the same return.",
        unit="ratio",
        entity="collection",
        job_kinds=("train.sampo",),
    ),
    _entry(
        "train/rl/singleton_anchor_fraction",
        "singleton_anchor_share",
        "Turns without a peer",
        "Fraction of sampled turns whose anchor state no other attempt in the group reached.",
        interpretation="These turns get no relative turn credit; rising values mean attempts diverge early.",
        unit="ratio",
        entity="collection",
        job_kinds=("train.sampo",),
    ),
    _entry(
        "train/rl/anchor_group_size_mean",
        "anchor_group_size",
        "Anchor group size",
        "Mean number of comparable turns contributing to each step-aware advantage anchor.",
        interpretation="Small groups provide weak relative evidence; compare this value across runs using the same sampling policy.",
        entity="collection",
        job_kinds=("train.sampo",),
    ),
    _entry(
        "train/rl/sparse_reward_projection_fraction",
        "step_reward_share",
        "Sparse-reward projection",
        "Fraction of sampled trajectories whose terminal reward was projected back across intermediate turns.",
        interpretation="A high value means SAMPO is relying heavily on its sparse-reward credit-assignment path.",
        unit="ratio",
        entity="collection",
        transform="one_minus",
        job_kinds=("train.sampo",),
    ),
    _entry(
        "data/examples",
        "data_examples",
        "Prepared examples",
        "Number of examples materialized into the immutable prepared dataset.",
        interpretation="Use this count to verify that the packaged dataset population matches the selected source.",
        entity="run",
        aggregation="sum",
        job_kinds=("data.prepare",),
    ),
    _entry(
        "data/bytes",
        "data_bytes",
        "Prepared bytes",
        "Byte size of the immutable prepared dataset content.",
        interpretation="Use it with example count and the retained dataset artifact to detect unexpected packaging changes.",
        unit="bytes",
        entity="run",
        aggregation="sum",
        job_kinds=("data.prepare",),
    ),
    _entry(
        "serve/probe_healthy",
        "probe_healthy",
        "Endpoint healthy",
        "Whether the managed endpoint returned a successful health response.",
        interpretation="A value of 100% confirms the endpoint process answered its health check.",
        unit="ratio",
        entity="run",
        aggregation="min",
        job_kinds=("serve.smoke",),
    ),
    _entry(
        "serve/probe_model_available",
        "probe_model_available",
        "Model available",
        "Whether model discovery exposed the exact model selected by the inference binding.",
        interpretation="A healthy server is not usable for this job unless the selected model is also available.",
        unit="ratio",
        entity="run",
        aggregation="min",
        job_kinds=("serve.smoke",),
    ),
    _entry(
        "serve/probe_latency_seconds",
        "probe_latency_seconds",
        "Probe latency",
        "Wall-clock time for the combined health and model-discovery probe.",
        interpretation="Use this as startup qualification evidence, not as inference latency.",
        unit="s",
        entity="run",
        aggregation="max",
        job_kinds=("serve.smoke",),
    ),
    _entry(
        "serve/run/output_tokens_measured",
        "serve_output_tokens",
        "Measured output tokens",
        "Successfully generated output tokens in the finalized benchmark point.",
        interpretation="Observatory divides this counter by the matching measurement duration to calculate aggregate throughput.",
        unit="tokens",
        entity="run",
        aggregation="sum",
        job_kinds=("serve.benchmark",),
    ),
    _entry(
        "serve/run/measurement_duration_s",
        "serve_measurement_seconds",
        "Measurement duration",
        "Wall-clock duration of the finalized measured inference window.",
        interpretation="This is the denominator for aggregate output-token throughput.",
        unit="s",
        entity="run",
        aggregation="sum",
        job_kinds=("serve.benchmark",),
    ),
    _entry(
        "serve/run/requests_measured",
        "serve_requests",
        "Measured requests",
        "Number of non-warmup requests successfully retained for the point.",
        interpretation="Decision-grade latency requires the same complete request population in inference traces.",
        entity="run",
        aggregation="sum",
        job_kinds=("serve.benchmark",),
    ),
    _entry(
        "serve/run/concurrency",
        "serve_concurrency",
        "Concurrency",
        "Number of requests allowed to execute concurrently at this measured operating point.",
        interpretation="Concurrency is a search variable used to characterize the fixed hardware target, not a product constraint.",
        entity="run",
        aggregation="max",
        job_kinds=("serve.benchmark",),
    ),
    _entry(
        "serve/run/context_tokens",
        "serve_context_tokens",
        "Context allocation",
        "Maximum context allocation configured for the serving runtime.",
        interpretation="It must be at least the context window required by the product.",
        unit="tokens",
        entity="run",
        aggregation="max",
        job_kinds=("serve.benchmark",),
    ),
    _entry(
        "serve/backend/peak_vram_bytes",
        "serve_peak_vram_bytes",
        "Peak GPU memory",
        "Highest observed GPU memory allocation during the benchmark.",
        interpretation="Use it to understand target headroom; it is not a substitute for KV-cache capacity evidence.",
        unit="bytes",
        entity="run",
        aggregation="max",
        job_kinds=("serve.benchmark",),
    ),
    _entry(
        "train/rl/importance_sampling_ratio_clamped_fraction",
        "correction_clamp_share",
        "Correction clamped",
        "Share of tokens whose sampler correction was clamped.",
        entity="update",
        job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
    ),
    _entry(
        "eval/run/rollouts_attempted",
        "eval_rollouts_attempted",
        "Rollouts attempted",
        "Evaluation rollouts attempted.",
        entity="run",
        aggregation="sum",
        job_kinds=("eval.domain", "eval.general"),
    ),
    # TRL's per-round active-sampling counts, one name per round (rounds count
    # from 1 and are bounded by the settings' max_candidate_batches; described
    # here for up to ACTIVE_SAMPLING_CATALOG_ROUNDS). Not semantic measures:
    # the round is part of the name, and most updates run only the first round.
    *(
        _entry(
            f"train/rl/active_sampling_round_{round_index}_{kind}_groups",
            f"active_sampling_round_{round_index}_{kind}_groups",
            f"Active-sampling round {round_index} {kind} groups",
            description.format(round_index=round_index),
            interpretation=(
                "Compare requested with generated to see the oversampling each round added, and retained with "
                "requested to see how many groups had reward spread; later rounds appear only when earlier ones "
                "did not fill the update."
            ),
            aggregation="sum",
            job_kinds=("train.grpo", "train.sampo"),
        )
        for round_index in range(1, ACTIVE_SAMPLING_CATALOG_ROUNDS + 1)
        for kind, description in (
            ("requested", "Prompt groups active-sampling round {round_index} still needed to fill the update."),
            (
                "generated",
                "Prompt groups active-sampling round {round_index} generated, including oversampled groups.",
            ),
            ("retained", "Prompt groups from active-sampling round {round_index} with reward spread that were kept."),
        )
    ),
    _entry(
        "train/rl/collection_updates",
        "planned_updates",
        "Planned updates per collection",
        "Optimizer updates the trainer planned for the collection when it admitted it.",
        unit="updates",
        entity="collection",
        aggregation="last",
        job_kinds=RESOLVED_UPDATE_KINDS,
    ),
    # One rate per episode ending (`posttrain.common.EpisodeEnding`); the
    # per-rollout label is the `rollout.ending` dimension.
    *(
        _entry(
            f"train/rl/ending_{ending}_rate",
            f"ending_{ending}_rate",
            f"Ending: {ending.replace('_', ' ')}",
            f"Share of the collection's attempted rollouts that ended {ending}. {meaning}",
            unit="ratio",
            entity="collection",
            job_kinds=("train.capo", "train.gdpo", "train.grpo", "train.sampo"),
        )
        for ending, meaning in EPISODE_ENDING_DESCRIPTIONS.items()
    ),
)
CATALOG_BY_METRIC: dict[str, MetricEntry] = {entry.metric: entry for entry in METRIC_CATALOG}


def metric_help(*metrics: str) -> tuple[MetricHelp, ...]:
    return tuple(CATALOG_BY_METRIC[metric].help() for metric in metrics)


__all__ = [
    "ACTIVE_SAMPLING_CATALOG_ROUNDS",
    "CATALOG_BY_METRIC",
    "METRIC_CATALOG",
    "RESOLVED_UPDATE_KINDS",
    "MetricEntry",
    "metric_help",
]
