"""Pinned foundation model variants and renderer contracts."""

from .lfm25 import LFM25_RENDERER_CONTRACT, LFM_25_12B_THINKING
from .qwen35 import (
    QWEN35_RENDERER_CONTRACT,
    QWEN35_THINKING_RENDERER_CONTRACT,
    QWEN_35_08B,
    QWEN_35_2B,
)

RENDERER_CONTRACTS = {
    QWEN35_RENDERER_CONTRACT.id: QWEN35_RENDERER_CONTRACT,
    QWEN35_THINKING_RENDERER_CONTRACT.id: QWEN35_THINKING_RENDERER_CONTRACT,
    LFM25_RENDERER_CONTRACT.id: LFM25_RENDERER_CONTRACT,
}

FOUNDATION_VARIANTS = {
    QWEN_35_08B.id: QWEN_35_08B,
    QWEN_35_2B.id: QWEN_35_2B,
    LFM_25_12B_THINKING.id: LFM_25_12B_THINKING,
}

__all__ = [
    "FOUNDATION_VARIANTS",
    "LFM25_RENDERER_CONTRACT",
    "LFM_25_12B_THINKING",
    "QWEN35_RENDERER_CONTRACT",
    "QWEN35_THINKING_RENDERER_CONTRACT",
    "QWEN_35_08B",
    "QWEN_35_2B",
    "RENDERER_CONTRACTS",
]
