"""Framework-neutral contracts for the post-training platform."""

from .artifacts import (
    ArtifactRef,
    HubModelRef,
    JsonValue,
    LocalArtifactRef,
    ProducedArtifact,
    PublishedArtifact,
    StoredArtifactRef,
    TrackioArtifactRef,
)
from .catalog import Catalog, CatalogLayer, CatalogRef, Resolved
from .errors import ContractError, OperationCancelled, PostTrainError
from .execution import (
    CancellationToken,
    EventObservation,
    MetricBatchObservation,
    MetricObservation,
    NullObserver,
    Observer,
    RunContext,
    SignalSource,
    SignalSourceKind,
    TraceFactSet,
    TraceFactUpdateObservation,
    TraceObservation,
    TraceRewardComponent,
)
from .hosted import (
    ExternalInferenceService,
    HostedInferenceBinding,
    HostedModel,
    JudgeInferenceBinding,
    ProviderEndpointProfile,
    validate_secret_free_http_url,
)
from .jsonl_journal import AppendOnlyJsonlTailer, JsonlJournalStats
from .models import (
    ChatTemplate,
    ConversationProfile,
    ModelArtifactDescriptor,
    ModelCapabilities,
    ModelVariant,
    ReasoningMode,
    RendererContract,
    ToolCallProtocol,
)
from .selections import ExecutionTarget, HardwareCapabilities, InferenceBinding, Workload
from .validation import CheckOutcome, ConfigurationIssue, SettingOrigin

__all__ = [
    "ArtifactRef",
    "AppendOnlyJsonlTailer",
    "CancellationToken",
    "Catalog",
    "CatalogLayer",
    "CatalogRef",
    "ChatTemplate",
    "CheckOutcome",
    "ConfigurationIssue",
    "ContractError",
    "EventObservation",
    "ExternalInferenceService",
    "ExecutionTarget",
    "HubModelRef",
    "HostedModel",
    "HostedInferenceBinding",
    "JudgeInferenceBinding",
    "ProviderEndpointProfile",
    "HardwareCapabilities",
    "InferenceBinding",
    "JsonValue",
    "JsonlJournalStats",
    "LocalArtifactRef",
    "MetricObservation",
    "MetricBatchObservation",
    "ModelCapabilities",
    "ModelArtifactDescriptor",
    "ModelVariant",
    "ConversationProfile",
    "ReasoningMode",
    "RendererContract",
    "ToolCallProtocol",
    "NullObserver",
    "Observer",
    "OperationCancelled",
    "PostTrainError",
    "ProducedArtifact",
    "PublishedArtifact",
    "Resolved",
    "RunContext",
    "SignalSource",
    "SignalSourceKind",
    "StoredArtifactRef",
    "SettingOrigin",
    "TraceFactSet",
    "TraceFactUpdateObservation",
    "TraceObservation",
    "TraceRewardComponent",
    "TrackioArtifactRef",
    "Workload",
    "validate_secret_free_http_url",
]
