"""Render the published image manifest from real registry state.

Kept separate from the publishing side effects so the exact bytes that ship in
a release can be produced and checked without a registry.
"""

from __future__ import annotations

from collections.abc import Mapping

from posttrain.runtime_images.manifest import PublishedImage

_HEADER = """\
# Published runtime image manifest.
#
# GENERATED by `posttrain-release images publish`. Do not edit by hand: the
# digests and lock hashes below are read back from the registry after a real
# build, and hand-maintaining them is what previously allowed a published
# job-kind image and its framework to disagree undetected.
#
# `lock_digest` is the SHA-256 of the referenced `constraint_lock` bytes and is
# the value published as the `org.carbonteq.posttrain.lock-digest` OCI label.
#
# `default_prefix` is where the FRAMEWORK publishes, once per release. It is not
# a project's registry: a project pushes its own actual-job images to
# POSTTRAIN_REGISTRY, which may also mirror these images. Digests are
# content-addressed, so mirroring preserves identity across registries.
"""


def _quote(value: str) -> str:
    if '"' in value or "\\" in value:
        raise ValueError(f"manifest values must not need escaping: {value!r}")
    return f'"{value}"'


def _render_image(image: PublishedImage) -> list[str]:
    lines = [
        f"repository = {_quote(image.repository)}",
        f"digest = {_quote(image.digest)}",
        f"lock_digest = {_quote(image.lock_digest)}",
        f"constraint_lock = {_quote(image.constraint_lock.as_posix())}",
    ]
    if image.provided_packages:
        rendered = ", ".join(_quote(name) for name in image.provided_packages)
        lines.append(f"provided_packages = [{rendered}]")
    if image.backend_constraint_lock is not None:
        if image.backend_lock_digest is None:
            raise ValueError(f"{image.name}: backend constraint lock has no digest")
        lines.extend(
            (
                f"backend_constraint_lock = {_quote(image.backend_constraint_lock.as_posix())}",
                f"backend_lock_digest = {_quote(image.backend_lock_digest)}",
            )
        )
        if image.backend_provided_packages:
            rendered = ", ".join(_quote(name) for name in image.backend_provided_packages)
            lines.append(f"backend_provided_packages = [{rendered}]")
    return lines


def render_manifest(
    *,
    framework_version: str,
    default_prefix: str,
    base: PublishedImage,
    kinds: Mapping[str, PublishedImage],
    schema_version: int = 1,
) -> str:
    """Return the full text of a `published.toml`."""
    if not kinds:
        raise ValueError("a release must publish at least one job-kind image")

    lines = [
        _HEADER,
        f"schema_version = {schema_version}",
        f"framework_version = {_quote(framework_version)}",
        f"default_prefix = {_quote(default_prefix)}",
        "",
        "[base]",
        *_render_image(base),
    ]
    for variant in sorted(kinds):
        lines.extend(["", f"[kinds.{variant}]", *_render_image(kinds[variant])])
    return "\n".join(lines) + "\n"


__all__ = ["render_manifest"]
