/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export */
        post: operations["export_api_v1_exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/job-kinds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Kinds */
        get: operations["job_kinds_api_v1_job_kinds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/job-kinds/{job_kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Kind */
        get: operations["job_kind_api_v1_job_kinds__job_kind__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_v1_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare */
        post: operations["compare_api_v1_runs_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_key}/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alerts */
        get: operations["alerts_api_v1_runs__run_key__alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_key}/delta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Delta */
        get: operations["delta_api_v1_runs__run_key__delta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_key}/metric-series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Metric Series */
        post: operations["metric_series_api_v1_runs__run_key__metric_series_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_key}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_api_v1_runs__run_key__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_key}/semantic-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Semantic Summary */
        post: operations["semantic_summary_api_v1_runs__run_key__semantic_summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_key}/system-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Metrics */
        get: operations["system_metrics_api_v1_runs__run_key__system_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_key}/traces-evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Traces Evaluation */
        get: operations["traces_evaluation_api_v1_runs__run_key__traces_evaluation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_key}/traces/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trace Detail */
        get: operations["trace_detail_api_v1_runs__run_key__traces__trace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_key}/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run View */
        get: operations["run_view_api_v1_runs__run_key__view_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources */
        get: operations["sources_api_v1_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-packages/{work_package_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Work Package */
        get: operations["work_package_api_v1_work_packages__work_package_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        AlertSeverity: "info" | "warning" | "error";
        /** ArtifactLink */
        ArtifactLink: {
            artifact: components["schemas"]["StoredArtifact"];
            /**
             * Direction
             * @enum {string}
             */
            direction: "input" | "output";
            /** Kind */
            kind: string;
            /** Logical Name */
            logical_name: string;
        };
        /** ArtifactSet */
        ArtifactSet: {
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["ArtifactLink"][];
        };
        /** ChartView */
        ChartView: {
            /** Key */
            key: string;
            /** Question */
            question?: string | null;
            /** Series */
            series: components["schemas"]["MetricSeries"][];
            /** Title */
            title: string;
        };
        /** CompareRequest */
        CompareRequest: {
            /** Run Keys */
            run_keys: string[];
        };
        /** EvaluationRunView */
        EvaluationRunView: {
            /** Alerts */
            alerts: components["schemas"]["RunAlert"][];
            artifacts: components["schemas"]["ArtifactSet"];
            capabilities: components["schemas"]["TrackingCapabilities"];
            /** Charts */
            charts: components["schemas"]["ChartView"][];
            completeness: components["schemas"]["EvidenceCompleteness"];
            evaluation: components["schemas"]["TraceEvaluationView"];
            /**
             * Execution Targets
             * @default []
             */
            execution_targets: components["schemas"]["ExecutionTargetContext"][];
            locator: components["schemas"]["RunLocator"];
            /** Metric Help */
            metric_help: components["schemas"]["MetricHelp"][];
            /** Resolved Inputs */
            resolved_inputs?: {
                [key: string]: components["schemas"]["JsonPayload"];
            };
            run: components["schemas"]["RunSummary"];
            /** Schema Version */
            schema_version: number;
            /** Source Metadata */
            source_metadata?: {
                [key: string]: components["schemas"]["JsonPayload"];
            };
            /** Summary */
            summary: components["schemas"]["SummaryValue"][];
            /**
             * Trace Evaluation Enabled
             * @default true
             */
            trace_evaluation_enabled: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            view_kind: "job.evaluation";
        };
        /** EvaluationSlice */
        EvaluationSlice: {
            /** Count */
            count: number;
            /** Key */
            key: string;
            /** Mean Reward */
            mean_reward?: number | null;
            /** Success Rate */
            success_rate?: number | null;
        };
        /** EventRecord */
        EventRecord: {
            /** Attributes */
            attributes?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Name */
            name: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /** EvidenceCompleteness */
        EvidenceCompleteness: {
            /** Conditional Active */
            conditional_active: number;
            /** Conditional Available */
            conditional_available: number;
            /** Required Available */
            required_available: number;
            /** Required Total */
            required_total: number;
            /** Requirements */
            requirements: components["schemas"]["EvidenceRequirement"][];
            /** Research Ready */
            research_ready: boolean;
            state: components["schemas"]["EvidenceCompletenessState"];
        };
        /** @enum {string} */
        EvidenceCompletenessState: "complete" | "partial" | "insufficient";
        /** EvidenceRequirement */
        EvidenceRequirement: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            level: components["schemas"]["EvidenceRequirementLevel"];
            metrics: components["schemas"]["StringTuple"];
            /** @default [] */
            missing_metrics: components["schemas"]["StringTuple"];
            /** Reason */
            reason?: string | null;
            state: components["schemas"]["EvidenceRequirementState"];
        };
        /** @enum {string} */
        EvidenceRequirementLevel: "required" | "conditional" | "diagnostic";
        /** @enum {string} */
        EvidenceRequirementState: "available" | "missing" | "not_applicable";
        /** @enum {string} */
        EvidenceState: "available" | "missing" | "incomparable" | "not_run" | "stale" | "reused_from_framework";
        /**
         * ExecutionTargetContext
         * @description Immutable hardware context retained with the run's resolved selections.
         */
        ExecutionTargetContext: {
            /** Aggregate Memory Bytes */
            aggregate_memory_bytes?: number | null;
            /** Device Class */
            device_class?: string | null;
            /** Device Count */
            device_count?: number | null;
            /** Host Constraints */
            host_constraints?: {
                [key: string]: components["schemas"]["JsonPayload"];
            };
            /** Memory Bytes Per Device */
            memory_bytes_per_device?: number | null;
            /** Placement */
            placement?: {
                [key: string]: components["schemas"]["JsonPayload"];
            };
            /** Revision */
            revision?: string | null;
            /** @default [] */
            roles: components["schemas"]["StringTuple"];
            /** Selection Id */
            selection_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "complete" | "partial";
        };
        /** ExportRequest */
        ExportRequest: {
            /**
             * Format
             * @default json
             * @enum {string}
             */
            format: "json" | "csv";
            /** @default [] */
            run_keys: components["schemas"]["StringTuple"];
            /** Work Package Id */
            work_package_id?: string | null;
        };
        /** GRPOAccelerationEvidence */
        GRPOAccelerationEvidence: {
            accepted_speculative_length: components["schemas"]["SummaryValue"];
            kv_cache_peak_usage: components["schemas"]["SummaryValue"];
            /** Mtp Selected */
            mtp_selected: boolean;
            /** Quantized Kv Cache Selected */
            quantized_kv_cache_selected: boolean;
            speculative_acceptance: components["schemas"]["SummaryValue"];
        };
        /**
         * GRPOProjection
         * @description GRPO-specific evidence consumed identically by HTTP, MCP, Python, and UI.
         */
        GRPOProjection: {
            acceleration: components["schemas"]["GRPOAccelerationEvidence"];
            rollout_population: components["schemas"]["GRPORolloutPopulation"];
        };
        /** GRPORolloutPopulation */
        GRPORolloutPopulation: {
            attempted: components["schemas"]["SummaryValue"];
            completed: components["schemas"]["SummaryValue"];
            failed: components["schemas"]["SummaryValue"];
            truncated: components["schemas"]["SummaryValue"];
            unscorable: components["schemas"]["SummaryValue"];
        };
        /** GenericRunView */
        GenericRunView: {
            artifacts: components["schemas"]["ArtifactSet"];
            capabilities: components["schemas"]["TrackingCapabilities"];
            /** Events */
            events: components["schemas"]["EventRecord"][];
            /**
             * Execution Targets
             * @default []
             */
            execution_targets: components["schemas"]["ExecutionTargetContext"][];
            locator: components["schemas"]["RunLocator"];
            metric_catalog: components["schemas"]["MetricCatalog"];
            /** Resolved Inputs */
            resolved_inputs: {
                [key: string]: components["schemas"]["JsonPayload"];
            };
            run: components["schemas"]["RunSummary"];
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            selected_series?: components["schemas"]["MetricSeriesSet"] | null;
            /** Source Metadata */
            source_metadata: {
                [key: string]: components["schemas"]["JsonPayload"];
            };
            /** Trace Count */
            trace_count: number;
            /** Trace Evaluation Enabled */
            trace_evaluation_enabled: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            view_kind: "generic";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** @description Any JSON-compatible value. */
        JsonPayload: unknown;
        JsonScalar: string | number | boolean | null;
        /**
         * JsonValue
         * @description Any JSON-compatible value.
         */
        JsonValue: unknown;
        /** MetricCatalog */
        MetricCatalog: {
            /** Namespaces */
            namespaces: components["schemas"]["MetricNamespace"][];
            /** Total */
            total: number;
        };
        /**
         * MetricHelp
         * @description Human-readable semantics for one provider-neutral metric name.
         */
        MetricHelp: {
            /** Caveat */
            caveat?: string | null;
            /** Description */
            description: string;
            /** Interpretation */
            interpretation: string;
            /** Label */
            label: string;
            /** Metric */
            metric: string;
            /** Unit */
            unit?: string | null;
        };
        /** MetricNamespace */
        MetricNamespace: {
            /** Metrics */
            metrics: string[];
            /** Name */
            name: string;
        };
        /** MetricPoint */
        MetricPoint: {
            /** Attributes */
            attributes?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Observed At */
            observed_at?: string | null;
            /** Step */
            step?: number | null;
            /** Value */
            value: number;
        };
        /** MetricSeries */
        MetricSeries: {
            /** Name */
            name: string;
            /**
             * Points
             * @default []
             */
            points: components["schemas"]["MetricPoint"][];
        };
        /** MetricSeriesQuery */
        MetricSeriesQuery: {
            /** End Step */
            end_step?: number | null;
            /**
             * Max Points
             * @default 400
             */
            max_points: number;
            names: components["schemas"]["StringTuple"];
            /** Start Step */
            start_step?: number | null;
        };
        /** MetricSeriesSet */
        MetricSeriesSet: {
            /**
             * Downsampled
             * @default false
             */
            downsampled: boolean;
            /**
             * Requested Points
             * @default 0
             */
            requested_points: number;
            /**
             * Returned Points
             * @default 0
             */
            returned_points: number;
            /** Series */
            series: components["schemas"]["MetricSeries"][];
        };
        /** RunAlert */
        RunAlert: {
            /** Field */
            field?: string | null;
            /** Id */
            id: string;
            /** Message */
            message: string;
            severity: components["schemas"]["AlertSeverity"];
        };
        /** RunLocator */
        RunLocator: {
            /** Run Id */
            run_id: string;
            /** Source Id */
            source_id: string;
        };
        /** @enum {string} */
        RunStatus: "running" | "succeeded" | "partial" | "failed" | "cancelled" | "unsupported";
        /** RunSummary */
        RunSummary: {
            /** Display Name */
            display_name: string;
            error?: components["schemas"]["SafeRunError"] | null;
            /** Finished At */
            finished_at?: string | null;
            /** Job Definition Version */
            job_definition_version: string;
            /** Job Kind */
            job_kind: string;
            /** Project Id */
            project_id: string;
            /** Provider */
            provider: string;
            /** Provider Run Id */
            provider_run_id?: string | null;
            /** Run Id */
            run_id: string;
            stage: components["schemas"]["Stage"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["RunStatus"];
            /** Work Package Id */
            work_package_id: string;
        };
        /**
         * RunView
         * @description Registered metric-job projection. Kept as the stable Python name.
         */
        RunView: {
            /** Alerts */
            alerts: components["schemas"]["RunAlert"][];
            artifacts: components["schemas"]["ArtifactSet"];
            capabilities: components["schemas"]["TrackingCapabilities"];
            /** Charts */
            charts: components["schemas"]["ChartView"][];
            completeness: components["schemas"]["EvidenceCompleteness"];
            /**
             * Execution Targets
             * @default []
             */
            execution_targets: components["schemas"]["ExecutionTargetContext"][];
            grpo?: components["schemas"]["GRPOProjection"] | null;
            locator?: components["schemas"]["RunLocator"] | null;
            /** Metric Help */
            metric_help: components["schemas"]["MetricHelp"][];
            /** Resolved Inputs */
            resolved_inputs?: {
                [key: string]: components["schemas"]["JsonPayload"];
            };
            run: components["schemas"]["RunSummary"];
            /** Schema Version */
            schema_version: number;
            /** Source Metadata */
            source_metadata?: {
                [key: string]: components["schemas"]["JsonPayload"];
            };
            /** Summary */
            summary: components["schemas"]["SummaryValue"][];
            /** Trace Count */
            trace_count: number;
            /** Trace Evaluation Enabled */
            trace_evaluation_enabled: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            view_kind: "job.metrics";
        };
        /** RunViewResponse */
        RunViewResponse: {
            /** Fallback Reason */
            fallback_reason?: string | null;
            requested_mode: components["schemas"]["ViewMode"];
            /**
             * Resolved Mode
             * @enum {string}
             */
            resolved_mode: "job" | "generic";
            view: components["schemas"]["RunViewVariant"];
        };
        RunViewVariant: components["schemas"]["RunView"] | components["schemas"]["EvaluationRunView"] | components["schemas"]["GenericRunView"];
        /** SafeRunError */
        SafeRunError: {
            /** Message */
            message: string;
            /** Type */
            type: string;
        };
        /** SemanticSummaryRequest */
        SemanticSummaryRequest: {
            /** @default [] */
            metric_names: components["schemas"]["StringTuple"];
            /**
             * Scope
             * @default run
             * @enum {string}
             */
            scope: "run" | "metrics" | "evaluation" | "trace";
            /** Trace Id */
            trace_id?: string | null;
        };
        /** @enum {string} */
        Stage: "screen" | "train" | "qualify";
        /** StoredArtifact */
        StoredArtifact: {
            /** Digest */
            digest?: string | null;
            /** Name */
            name: string;
            /** Namespace */
            namespace: string;
            /** Provider */
            provider: string;
            /** Provider Metadata */
            provider_metadata?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Version */
            version: string;
        };
        StringTuple: string[];
        /** SummaryValue */
        SummaryValue: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Metric */
            metric?: string | null;
            state: components["schemas"]["EvidenceState"];
            /** Unit */
            unit?: string | null;
            value?: components["schemas"]["JsonPayload"];
        };
        /** TraceEvaluationView */
        TraceEvaluationView: {
            /** Expected */
            expected?: number | null;
            /**
             * Failures
             * @default 0
             */
            failures: number;
            /** Included */
            included: number;
            /**
             * Live
             * @default false
             */
            live: boolean;
            /** Mean Reward */
            mean_reward?: number | null;
            /** Next Cursor */
            next_cursor?: string | null;
            /** Scanned */
            scanned: number;
            /**
             * Slices
             * @default []
             */
            slices: components["schemas"]["EvaluationSlice"][];
            /**
             * State
             * @enum {string}
             */
            state: "complete" | "partial" | "unavailable";
            /** Success Rate */
            success_rate?: number | null;
            /**
             * Traces
             * @default []
             */
            traces: components["schemas"]["TraceSummary"][];
            /**
             * Truncated
             * @default 0
             */
            truncated: number;
        };
        /** TraceSummary */
        TraceSummary: {
            /** Error */
            error?: string | null;
            /** External Id */
            external_id: string;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Reward */
            reward?: number | null;
            /** Success */
            success?: boolean | null;
            /** Task */
            task?: string | null;
            /** Tokens */
            tokens?: number | null;
            /** Tool Calls */
            tool_calls?: number | null;
            /** Trace Type */
            trace_type: string;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /** TrackingCapabilities */
        TrackingCapabilities: {
            /**
             * Artifact Lineage
             * @default true
             */
            artifact_lineage: boolean;
            /**
             * Artifacts
             * @default true
             */
            artifacts: boolean;
            /**
             * Live Metrics
             * @default true
             */
            live_metrics: boolean;
            /**
             * Live Traces
             * @default false
             */
            live_traces: boolean;
            /** Provider */
            provider: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** @enum {string} */
        ViewMode: "auto" | "job" | "generic";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    export_api_v1_exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_kinds_api_v1_job_kinds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    job_kind_api_v1_job_kinds__job_kind__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_api_v1_runs_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                work_package_id?: string | null;
                job_kind?: string[];
                status?: string[];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_api_v1_runs_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alerts_api_v1_runs__run_key__alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delta_api_v1_runs__run_key__delta_get: {
        parameters: {
            query?: {
                cursor?: string | null;
            };
            header?: never;
            path: {
                run_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metric_series_api_v1_runs__run_key__metric_series_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetricSeriesQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_api_v1_runs__run_key__metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    semantic_summary_api_v1_runs__run_key__semantic_summary_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SemanticSummaryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_metrics_api_v1_runs__run_key__system_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    traces_evaluation_api_v1_runs__run_key__traces_evaluation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trace_detail_api_v1_runs__run_key__traces__trace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_key: string;
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_view_api_v1_runs__run_key__view_get: {
        parameters: {
            query?: {
                mode?: "auto" | "job" | "generic";
                metric?: string[];
            };
            header?: never;
            path: {
                run_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunViewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_api_v1_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    work_package_api_v1_work_packages__work_package_id__get: {
        parameters: {
            query?: {
                project_id?: string | null;
                source_id?: string | null;
            };
            header?: never;
            path: {
                work_package_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
