/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export */
        post: operations["export_api_v1_exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/job-kinds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Kinds */
        get: operations["job_kinds_api_v1_job_kinds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/job-kinds/{job_kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Kind */
        get: operations["job_kind_api_v1_job_kinds__job_kind__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_v1_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare */
        post: operations["compare_api_v1_runs_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/locate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Locate Run */
        get: operations["locate_run_api_v1_runs_locate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_key}/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alerts */
        get: operations["alerts_api_v1_runs__run_key__alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_key}/comparison-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Comparison Key */
        get: operations["comparison_key_api_v1_runs__run_key__comparison_key_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_key}/delta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Delta */
        get: operations["delta_api_v1_runs__run_key__delta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_key}/metric-series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Metric Series */
        post: operations["metric_series_api_v1_runs__run_key__metric_series_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_key}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_api_v1_runs__run_key__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_key}/semantic-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Semantic Summary */
        post: operations["semantic_summary_api_v1_runs__run_key__semantic_summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_key}/system-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Metrics */
        get: operations["system_metrics_api_v1_runs__run_key__system_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_key}/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trace Summaries */
        get: operations["trace_summaries_api_v1_runs__run_key__traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_key}/traces-evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Traces Evaluation */
        get: operations["traces_evaluation_api_v1_runs__run_key__traces_evaluation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_key}/traces/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trace Detail */
        get: operations["trace_detail_api_v1_runs__run_key__traces__trace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_key}/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run View */
        get: operations["run_view_api_v1_runs__run_key__view_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/serving-capacity/work-packages/{work_package_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serving Capacity Work Package */
        get: operations["serving_capacity_work_package_api_v1_serving_capacity_work_packages__work_package_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources */
        get: operations["sources_api_v1_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Sources */
        post: operations["refresh_sources_api_v1_sources_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-packages/{work_package_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Work Package */
        get: operations["work_package_api_v1_work_packages__work_package_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        AlertSeverity: "info" | "warning" | "error";
        /** ArtifactLink */
        ArtifactLink: {
            artifact: components["schemas"]["StoredArtifact"];
            /**
             * Direction
             * @enum {string}
             */
            direction: "input" | "output";
            /** Kind */
            kind: string;
            /** Logical Name */
            logical_name: string;
        };
        /** ArtifactSet */
        ArtifactSet: {
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["ArtifactLink"][];
        };
        /** BenchmarkPopulationView */
        BenchmarkPopulationView: {
            /** Cohort */
            cohort?: string | null;
            /** Corpus Digest */
            corpus_digest?: string | null;
            /** Corpus Id */
            corpus_id?: string | null;
            /** Corpus Revision */
            corpus_revision?: string | null;
            /**
             * Correctness Scored
             * @default false
             * @constant
             */
            correctness_scored: false;
            /** Input Tokens Mean */
            input_tokens_mean?: number | null;
            /** Input Tokens P95 */
            input_tokens_p95?: number | null;
            /** Measured Records */
            measured_records?: number | null;
            /**
             * Output Length Policy
             * @default unknown
             * @enum {string}
             */
            output_length_policy: "fixed" | "maximum" | "unknown";
            /** Output Target Hit Rate */
            output_target_hit_rate?: number | null;
            /** Output Token Budget */
            output_token_budget?: number | null;
            /** Renderer */
            renderer?: string | null;
            /** Requested Records */
            requested_records?: number | null;
            /** Shape Id */
            shape_id?: string | null;
            /** Suite Id */
            suite_id?: string | null;
        };
        /** ChartView */
        ChartView: {
            /** Key */
            key: string;
            /** Question */
            question?: string | null;
            /** Series */
            series: components["schemas"]["MetricSeries"][];
            /** Title */
            title: string;
        };
        /** CompareRequest */
        CompareRequest: {
            /** Run Keys */
            run_keys: string[];
        };
        /**
         * EvaluationBreakdown
         * @description One declared compound report with structured groups.
         */
        EvaluationBreakdown: {
            /** Dimension Labels */
            dimension_labels: [
                string,
                string
            ];
            /** Dimensions */
            dimensions: [
                string,
                string
            ];
            /**
             * Excluded
             * @default 0
             */
            excluded: number;
            /**
             * Groups
             * @default []
             */
            groups: components["schemas"]["EvaluationBreakdownGroup"][];
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Presentation
             * @default matrix
             * @constant
             */
            presentation: "matrix";
        };
        /**
         * EvaluationBreakdownGroup
         * @description Coverage-aware aggregate for one compound facet combination.
         */
        EvaluationBreakdownGroup: {
            /** Count */
            count: number;
            /** Failures */
            failures: number;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Mean Reward */
            mean_reward?: number | null;
            /** Scored */
            scored: number;
            /** Success Rate */
            success_rate?: number | null;
            /** Truncated */
            truncated: number;
            /** Values */
            values: components["schemas"]["EvaluationBreakdownValue"][];
        };
        /**
         * EvaluationBreakdownSpec
         * @description Run-owned compound grouping over declared facet dimensions.
         */
        EvaluationBreakdownSpec: {
            /** Dimensions */
            dimensions: [
                string,
                string
            ];
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Missing
             * @default exclude
             * @enum {string}
             */
            missing: "exclude" | "bucket";
            /**
             * Multi Value
             * @default reject
             * @enum {string}
             */
            multi_value: "reject" | "cross";
            /**
             * Presentation
             * @default matrix
             * @constant
             */
            presentation: "matrix";
        };
        /**
         * EvaluationBreakdownValue
         * @description One structured dimension value inside a compound group.
         */
        EvaluationBreakdownValue: {
            /** Dimension */
            dimension: string;
            /** Dimension Label */
            dimension_label: string;
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /**
         * EvaluationDistribution
         * @description Observed distribution for one request-level evaluation signal.
         */
        EvaluationDistribution: {
            /** Maximum */
            maximum: number;
            /** Mean */
            mean: number;
            /** P50 */
            p50: number;
            /** P95 */
            p95: number;
            /** Samples */
            samples: number;
        };
        /**
         * EvaluationFacet
         * @description Multi-label aggregate used to explain a task population by capability.
         */
        EvaluationFacet: {
            /** Count */
            count: number;
            /** Dimension */
            dimension: string;
            /** Dimension Label */
            dimension_label: string;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Mean Reward */
            mean_reward?: number | null;
            /** Success Rate */
            success_rate?: number | null;
        };
        /**
         * EvaluationFacetSpec
         * @description Resolved environment declaration for one native task-data facet.
         */
        EvaluationFacetSpec: {
            /** Dimension */
            dimension: string;
            /** Field */
            field: string;
            /** Label */
            label: string;
            /**
             * Transform
             * @default identity
             * @enum {string}
             */
            transform: "identity" | "prefix_before_colon";
        };
        /**
         * EvaluationMetadata
         * @description Evaluation identity and metric semantics used to build the Overview.
         */
        EvaluationMetadata: {
            /**
             * Breakdown Specs
             * @default []
             */
            breakdown_specs: components["schemas"]["EvaluationBreakdownSpec"][];
            /** Category */
            category?: string | null;
            /** Contract Id */
            contract_id?: string | null;
            /**
             * Contract State
             * @default legacy
             * @enum {string}
             */
            contract_state: "versioned" | "legacy" | "unsupported";
            /** Contract Version */
            contract_version?: number | null;
            /** Dataset */
            dataset?: string | null;
            /** Dataset Revision */
            dataset_revision?: string | null;
            /**
             * Facet Specs
             * @default []
             */
            facet_specs: components["schemas"]["EvaluationFacetSpec"][];
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Metrics
             * @default []
             */
            metrics: components["schemas"]["EvaluationMetricDefinition"][];
            /** Package */
            package?: string | null;
            /** Pass Rate Basis */
            pass_rate_basis?: string | null;
            /** Pass Rate Metric */
            pass_rate_metric?: string | null;
            /** Primary Metric */
            primary_metric?: string | null;
            /** Primary Metric Label */
            primary_metric_label?: string | null;
            /** Source Revision */
            source_revision?: string | null;
            /** Split */
            split?: string | null;
            success_definition?: components["schemas"]["EvaluationSuccessDefinition"] | null;
        };
        /**
         * EvaluationMetricDefinition
         * @description The native metric vocabulary advertised by an evaluation.
         */
        EvaluationMetricDefinition: {
            /** Label */
            label: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "primary_reward" | "reward_component" | "diagnostic" | "success";
        };
        /**
         * EvaluationPerformance
         * @description Efficiency evidence computed from the same trace population as quality.
         */
        EvaluationPerformance: {
            completion_tokens?: components["schemas"]["EvaluationDistribution"] | null;
            latency_ms?: components["schemas"]["EvaluationDistribution"] | null;
            thinking_tokens?: components["schemas"]["EvaluationDistribution"] | null;
            tool_calls?: components["schemas"]["EvaluationDistribution"] | null;
        };
        /** EvaluationRunView */
        EvaluationRunView: {
            /** Alerts */
            alerts: components["schemas"]["RunAlert"][];
            artifacts: components["schemas"]["ArtifactSet"];
            capabilities: components["schemas"]["TrackingCapabilities"];
            /** Charts */
            charts: components["schemas"]["ChartView"][];
            /** Comparison Key */
            comparison_key: string;
            completeness: components["schemas"]["EvidenceCompleteness"];
            evaluation: components["schemas"]["TraceEvaluationView"];
            /**
             * Execution Targets
             * @default []
             */
            execution_targets: components["schemas"]["ExecutionTargetContext"][];
            locator: components["schemas"]["RunLocator"];
            /** Metric Help */
            metric_help: components["schemas"]["MetricHelp"][];
            /** Resolved Inputs */
            resolved_inputs?: {
                [key: string]: components["schemas"]["JsonPayload"];
            };
            run: components["schemas"]["RunSummary"];
            /** Schema Version */
            schema_version: number;
            /** Source Metadata */
            source_metadata?: {
                [key: string]: components["schemas"]["JsonPayload"];
            };
            /** Summary */
            summary: components["schemas"]["SummaryValue"][];
            /**
             * Trace Evaluation Enabled
             * @default true
             */
            trace_evaluation_enabled: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            view_kind: "job.evaluation";
        };
        /** EvaluationSlice */
        EvaluationSlice: {
            /** Count */
            count: number;
            /** Description */
            description?: string | null;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Mean Reward */
            mean_reward?: number | null;
            metadata?: components["schemas"]["TaskSliceMetadata"] | null;
            /** Success Rate */
            success_rate?: number | null;
        };
        /**
         * EvaluationSuccessDefinition
         * @description Normalized run-owned predicate used to calculate semantic pass/fail.
         */
        EvaluationSuccessDefinition: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Missing
             * @default error
             * @enum {string}
             */
            missing: "error" | "exclude";
            /**
             * Namespace
             * @enum {string}
             */
            namespace: "reward" | "metric";
            /**
             * Operator
             * @enum {string}
             */
            operator: "eq" | "gt" | "gte" | "lt" | "lte" | "between";
            /** Signal */
            signal: string;
            /**
             * Tolerance
             * @default 0
             */
            tolerance: number;
            /** Upper */
            upper?: number | null;
            /** Value */
            value: number;
        };
        /** EventRecord */
        EventRecord: {
            /** Attributes */
            attributes?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Name */
            name: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /** EvidenceCompleteness */
        EvidenceCompleteness: {
            /** Conditional Active */
            conditional_active: number;
            /** Conditional Available */
            conditional_available: number;
            /** Required Available */
            required_available: number;
            /** Required Total */
            required_total: number;
            /** Requirements */
            requirements: components["schemas"]["EvidenceRequirement"][];
            /** Research Ready */
            research_ready: boolean;
            state: components["schemas"]["EvidenceCompletenessState"];
        };
        /** @enum {string} */
        EvidenceCompletenessState: "complete" | "partial" | "insufficient";
        /** EvidenceRequirement */
        EvidenceRequirement: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            level: components["schemas"]["EvidenceRequirementLevel"];
            metrics: components["schemas"]["StringTuple"];
            /** @default [] */
            missing_metrics: components["schemas"]["StringTuple"];
            /** Reason */
            reason?: string | null;
            state: components["schemas"]["EvidenceRequirementState"];
        };
        /** @enum {string} */
        EvidenceRequirementLevel: "required" | "conditional" | "diagnostic";
        /** @enum {string} */
        EvidenceRequirementState: "available" | "missing" | "not_applicable";
        /** @enum {string} */
        EvidenceState: "available" | "missing" | "incomparable" | "not_run" | "stale" | "reused_from_framework";
        /**
         * ExecutionTargetContext
         * @description Immutable hardware context retained with the run's resolved selections.
         */
        ExecutionTargetContext: {
            /** Aggregate Memory Bytes */
            aggregate_memory_bytes?: number | null;
            /** Device Class */
            device_class?: string | null;
            /** Device Count */
            device_count?: number | null;
            /** Host Constraints */
            host_constraints?: {
                [key: string]: components["schemas"]["JsonPayload"];
            };
            /** Memory Bytes Per Device */
            memory_bytes_per_device?: number | null;
            /** Placement */
            placement?: {
                [key: string]: components["schemas"]["JsonPayload"];
            };
            /** Revision */
            revision?: string | null;
            /** @default [] */
            roles: components["schemas"]["StringTuple"];
            /** Selection Id */
            selection_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "complete" | "partial";
        };
        /** ExportRequest */
        ExportRequest: {
            /**
             * Format
             * @default json
             * @enum {string}
             */
            format: "json" | "csv";
            /** Project Id */
            project_id?: string | null;
            /** @default [] */
            run_keys: components["schemas"]["StringTuple"];
            /** Source Id */
            source_id?: string | null;
            /**
             * View
             * @default runs
             * @enum {string}
             */
            view: "runs" | "serving_capacity";
            /** Work Package Id */
            work_package_id?: string | null;
        };
        /** GRPOAccelerationEvidence */
        GRPOAccelerationEvidence: {
            accepted_speculative_length: components["schemas"]["SummaryValue"];
            kv_cache_peak_usage: components["schemas"]["SummaryValue"];
            /** Mtp Selected */
            mtp_selected: boolean;
            /** Quantized Kv Cache Selected */
            quantized_kv_cache_selected: boolean;
            speculative_acceptance: components["schemas"]["SummaryValue"];
        };
        /**
         * GRPOProjection
         * @description GRPO-specific evidence consumed identically by HTTP, MCP, Python, and UI.
         */
        GRPOProjection: {
            acceleration: components["schemas"]["GRPOAccelerationEvidence"];
            rollout_population: components["schemas"]["GRPORolloutPopulation"];
        };
        /** GRPORolloutPopulation */
        GRPORolloutPopulation: {
            attempted: components["schemas"]["SummaryValue"];
            completed: components["schemas"]["SummaryValue"];
            failed: components["schemas"]["SummaryValue"];
            missing: components["schemas"]["SummaryValue"];
            requested: components["schemas"]["SummaryValue"];
            truncated: components["schemas"]["SummaryValue"];
            unscorable: components["schemas"]["SummaryValue"];
        };
        /** GenericRunView */
        GenericRunView: {
            artifacts: components["schemas"]["ArtifactSet"];
            capabilities: components["schemas"]["TrackingCapabilities"];
            /** Events */
            events: components["schemas"]["EventRecord"][];
            /**
             * Execution Targets
             * @default []
             */
            execution_targets: components["schemas"]["ExecutionTargetContext"][];
            locator: components["schemas"]["RunLocator"];
            metric_catalog: components["schemas"]["MetricCatalog"];
            /** Resolved Inputs */
            resolved_inputs: {
                [key: string]: components["schemas"]["JsonPayload"];
            };
            run: components["schemas"]["RunSummary"];
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            selected_series?: components["schemas"]["MetricSeriesSet"] | null;
            /** Source Metadata */
            source_metadata: {
                [key: string]: components["schemas"]["JsonPayload"];
            };
            /** Trace Count */
            trace_count: number;
            /** Trace Evaluation Enabled */
            trace_evaluation_enabled: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            view_kind: "generic";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** @description Any JSON-compatible value. */
        JsonPayload: unknown;
        JsonScalar: string | number | boolean | null;
        /**
         * JsonValue
         * @description Any JSON-compatible value.
         */
        JsonValue: unknown;
        /** MetricCatalog */
        MetricCatalog: {
            /** Namespaces */
            namespaces: components["schemas"]["MetricNamespace"][];
            /** Total */
            total: number;
        };
        /**
         * MetricHelp
         * @description Human-readable semantics for one provider-neutral metric name.
         */
        MetricHelp: {
            /** Caveat */
            caveat?: string | null;
            /** Description */
            description: string;
            /** Interpretation */
            interpretation: string;
            /** Label */
            label: string;
            /** Metric */
            metric: string;
            /** Unit */
            unit?: string | null;
        };
        /** MetricNamespace */
        MetricNamespace: {
            /** Metrics */
            metrics: string[];
            /** Name */
            name: string;
        };
        /** MetricPoint */
        MetricPoint: {
            /** Attributes */
            attributes?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Observed At */
            observed_at?: string | null;
            /** Step */
            step?: number | null;
            /** Value */
            value: number;
        };
        /** MetricSeries */
        MetricSeries: {
            /** Name */
            name: string;
            /**
             * Points
             * @default []
             */
            points: components["schemas"]["MetricPoint"][];
        };
        /** MetricSeriesQuery */
        MetricSeriesQuery: {
            /** End Step */
            end_step?: number | null;
            /**
             * Max Points
             * @default 400
             */
            max_points: number;
            names: components["schemas"]["StringTuple"];
            /** Start Step */
            start_step?: number | null;
        };
        /** MetricSeriesSet */
        MetricSeriesSet: {
            /**
             * Downsampled
             * @default false
             */
            downsampled: boolean;
            /**
             * Requested Points
             * @default 0
             */
            requested_points: number;
            /**
             * Returned Points
             * @default 0
             */
            returned_points: number;
            /** Series */
            series: components["schemas"]["MetricSeries"][];
        };
        /** RunAlert */
        RunAlert: {
            /** Field */
            field?: string | null;
            /** Id */
            id: string;
            /** Message */
            message: string;
            severity: components["schemas"]["AlertSeverity"];
        };
        /** RunLocator */
        RunLocator: {
            /** Run Id */
            run_id: string;
            /** Source Id */
            source_id: string;
        };
        /** @enum {string} */
        RunStatus: "running" | "succeeded" | "partial" | "failed" | "cancelled" | "unsupported";
        /** RunSummary */
        RunSummary: {
            /** Display Name */
            display_name: string;
            error?: components["schemas"]["SafeRunError"] | null;
            /** Finished At */
            finished_at?: string | null;
            /** Job Definition Version */
            job_definition_version: string;
            /** Job Kind */
            job_kind: string;
            /** Project Id */
            project_id: string;
            /** Provider */
            provider: string;
            /** Provider Run Id */
            provider_run_id?: string | null;
            /** Run Id */
            run_id: string;
            stage: components["schemas"]["Stage"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["RunStatus"];
            /** Work Package Id */
            work_package_id: string;
        };
        /**
         * RunView
         * @description Registered metric-job projection. Kept as the stable Python name.
         */
        RunView: {
            /** Alerts */
            alerts: components["schemas"]["RunAlert"][];
            artifacts: components["schemas"]["ArtifactSet"];
            capabilities: components["schemas"]["TrackingCapabilities"];
            /** Charts */
            charts: components["schemas"]["ChartView"][];
            completeness: components["schemas"]["EvidenceCompleteness"];
            /**
             * Execution Targets
             * @default []
             */
            execution_targets: components["schemas"]["ExecutionTargetContext"][];
            grpo?: components["schemas"]["GRPOProjection"] | null;
            locator?: components["schemas"]["RunLocator"] | null;
            /** Metric Help */
            metric_help: components["schemas"]["MetricHelp"][];
            /** Resolved Inputs */
            resolved_inputs?: {
                [key: string]: components["schemas"]["JsonPayload"];
            };
            run: components["schemas"]["RunSummary"];
            /** Schema Version */
            schema_version: number;
            /** Source Metadata */
            source_metadata?: {
                [key: string]: components["schemas"]["JsonPayload"];
            };
            /** Summary */
            summary: components["schemas"]["SummaryValue"][];
            /** Trace Count */
            trace_count: number;
            /** Trace Evaluation Enabled */
            trace_evaluation_enabled: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            view_kind: "job.metrics";
        };
        /** RunViewResponse */
        RunViewResponse: {
            /** Fallback Reason */
            fallback_reason?: string | null;
            requested_mode: components["schemas"]["ViewMode"];
            /**
             * Resolved Mode
             * @enum {string}
             */
            resolved_mode: "job" | "generic";
            view: components["schemas"]["RunViewVariant"];
        };
        RunViewVariant: components["schemas"]["RunView"] | components["schemas"]["EvaluationRunView"] | components["schemas"]["ServingBenchmarkRunView"] | components["schemas"]["GenericRunView"];
        /** RuntimeSettingGroup */
        RuntimeSettingGroup: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Settings */
            settings: components["schemas"]["RuntimeSettingValue"][];
        };
        /** RuntimeSettingValue */
        RuntimeSettingValue: {
            /**
             * Importance
             * @default advanced
             * @enum {string}
             */
            importance: "primary" | "advanced" | "additional";
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * State
             * @enum {string}
             */
            state: "available" | "missing" | "redacted";
            /** Unit */
            unit?: string | null;
            value?: components["schemas"]["JsonPayload"];
        };
        /** SafeRunError */
        SafeRunError: {
            /** Message */
            message: string;
            /** Type */
            type: string;
        };
        /** SemanticSummaryRequest */
        SemanticSummaryRequest: {
            /** @default [] */
            metric_names: components["schemas"]["StringTuple"];
            /**
             * Scope
             * @default run
             * @enum {string}
             */
            scope: "run" | "metrics" | "evaluation" | "trace";
            /** Trace Id */
            trace_id?: string | null;
        };
        /** ServingBenchmarkRunView */
        ServingBenchmarkRunView: {
            /** Alerts */
            alerts: components["schemas"]["RunAlert"][];
            artifacts: components["schemas"]["ArtifactSet"];
            capabilities: components["schemas"]["TrackingCapabilities"];
            eligibility: components["schemas"]["ServingEligibility"];
            /** Execution Target Id */
            execution_target_id?: string | null;
            /**
             * Execution Targets
             * @default []
             */
            execution_targets: components["schemas"]["ExecutionTargetContext"][];
            /** Inference Backend */
            inference_backend?: string | null;
            /** Inference Binding Id */
            inference_binding_id?: string | null;
            locator: components["schemas"]["RunLocator"];
            /** Model Variant Id */
            model_variant_id?: string | null;
            /** Operating Points */
            operating_points: components["schemas"]["ServingOperatingPoint"][];
            population: components["schemas"]["BenchmarkPopulationView"];
            /** Question */
            question: string;
            /** Requirements */
            requirements: components["schemas"]["ServingRequirementView"][];
            /** Resolved Inputs */
            resolved_inputs?: {
                [key: string]: components["schemas"]["JsonPayload"];
            };
            run: components["schemas"]["RunSummary"];
            /** Runtime Settings */
            runtime_settings: components["schemas"]["RuntimeSettingGroup"][];
            /** Schema Version */
            schema_version: number;
            selected_point?: components["schemas"]["ServingOperatingPoint"] | null;
            /** Source Metadata */
            source_metadata?: {
                [key: string]: components["schemas"]["JsonPayload"];
            };
            /** Trace Count */
            trace_count: number;
            /**
             * Trace Evaluation Enabled
             * @default false
             */
            trace_evaluation_enabled: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            view_kind: "job.serving";
            /** Workload Id */
            workload_id?: string | null;
        };
        /** ServingEligibility */
        ServingEligibility: {
            /**
             * Calculator Version
             * @default serving-capacity-v1
             * @constant
             */
            calculator_version: "serving-capacity-v1";
            /** Label */
            label: string;
            /** Reason */
            reason: string;
            /** Requirements Digest */
            requirements_digest?: string | null;
            /**
             * Saturation State
             * @enum {string}
             */
            saturation_state: "saturated" | "unsaturated" | "unknown";
            /** Selected Sweep Index */
            selected_sweep_index?: number | null;
            state: components["schemas"]["ServingEligibilityState"];
        };
        /** @enum {string} */
        ServingEligibilityState: "eligible" | "below_capacity" | "latency_constrained" | "reliability_constrained" | "context_failed" | "unsaturated" | "insufficient_evidence";
        /** ServingOperatingPoint */
        ServingOperatingPoint: {
            /** Aggregate Output Tps */
            aggregate_output_tps?: number | null;
            /** Attempted Requests */
            attempted_requests: number;
            /** Completed Requests */
            completed_requests: number;
            /** Concurrency */
            concurrency: number;
            /** Context Tokens */
            context_tokens?: number | null;
            /**
             * Evidence State
             * @enum {string}
             */
            evidence_state: "complete" | "partial" | "legacy_single_point";
            /** Failed Requests */
            failed_requests: number;
            /** Failure Rate */
            failure_rate?: number | null;
            /** Input Tokens Mean */
            input_tokens_mean?: number | null;
            /** Input Tokens P95 */
            input_tokens_p95?: number | null;
            /** Kv Cache Peak Usage Ratio */
            kv_cache_peak_usage_ratio?: number | null;
            /** Measurement Seconds */
            measurement_seconds?: number | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Output Tokens Mean */
            output_tokens_mean?: number | null;
            /** Output Tokens P95 */
            output_tokens_p95?: number | null;
            /** P50 Tpot Ms */
            p50_tpot_ms?: number | null;
            /** P50 Ttft Ms */
            p50_ttft_ms?: number | null;
            /** P95 Tpot Ms */
            p95_tpot_ms?: number | null;
            /** P95 Ttft Ms */
            p95_ttft_ms?: number | null;
            /** Peak Vram Bytes */
            peak_vram_bytes?: number | null;
            /** Sweep Index */
            sweep_index: number;
            /** Terminal Status */
            terminal_status?: ("resource_exhausted" | "unsupported" | "failed") | null;
            /** Valid */
            valid: boolean;
            /** @default [] */
            violations: components["schemas"]["StringTuple"];
        };
        /** @enum {string} */
        ServingRequirementState: "pass" | "fail" | "unavailable";
        /** ServingRequirementView */
        ServingRequirementView: {
            /** Explanation */
            explanation: string;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Margin */
            margin?: number | null;
            /** Measured */
            measured?: number | null;
            /**
             * Operator
             * @enum {string}
             */
            operator: "gte" | "lte";
            state: components["schemas"]["ServingRequirementState"];
            /** Threshold */
            threshold?: number | null;
            /** Unit */
            unit: string;
        };
        /** SourceRefreshStatus */
        SourceRefreshStatus: {
            /** @default [] */
            discovered_source_ids: components["schemas"]["StringTuple"];
            /** Enabled */
            enabled: boolean;
            /** Error */
            error?: string | null;
            /** Last Attempt At */
            last_attempt_at?: string | null;
            /** Last Success At */
            last_success_at?: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "disabled" | "pending" | "refreshing" | "succeeded" | "failed";
        };
        /** @enum {string} */
        Stage: "screen" | "train" | "qualify";
        /** StoredArtifact */
        StoredArtifact: {
            /** Digest */
            digest?: string | null;
            /** Name */
            name: string;
            /** Namespace */
            namespace: string;
            /** Provider */
            provider: string;
            /** Provider Metadata */
            provider_metadata?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Version */
            version: string;
        };
        StringTuple: string[];
        /** SummaryValue */
        SummaryValue: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Metric */
            metric?: string | null;
            state: components["schemas"]["EvidenceState"];
            /** Unit */
            unit?: string | null;
            value?: components["schemas"]["JsonPayload"];
        };
        /**
         * TaskFacet
         * @description One native semantic attribute attached to an evaluation task.
         *
         *     Environments own the values; Observatory only retains their stable
         *     dimension/value identity and a human-readable presentation.
         */
        TaskFacet: {
            /** Dimension */
            dimension: string;
            /** Dimension Label */
            dimension_label: string;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /**
         * TaskSliceMetadata
         * @description Stable, human-readable identity for one evaluation task slice.
         *
         *     ``key`` remains the source task identity (which may be numeric, as in
         *     IFEval). Semantic facets are optional and must not be confused with that
         *     identity.
         */
        TaskSliceMetadata: {
            /** Category */
            category?: string | null;
            /** Dataset */
            dataset?: string | null;
            /** Dataset Revision */
            dataset_revision?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Facets
             * @default []
             */
            facets: components["schemas"]["TaskFacet"][];
            /** Index */
            index?: number | null;
            /**
             * Instruction Families
             * @default []
             */
            instruction_families: string[];
            /**
             * Instruction Ids
             * @default []
             */
            instruction_ids: string[];
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Seed */
            seed?: number | null;
            /** Split */
            split?: string | null;
        };
        /** TraceEvaluationView */
        TraceEvaluationView: {
            /**
             * Breakdowns
             * @default []
             */
            breakdowns: components["schemas"]["EvaluationBreakdown"][];
            /** Expected */
            expected?: number | null;
            /**
             * Facets
             * @default []
             */
            facets: components["schemas"]["EvaluationFacet"][];
            /**
             * Failures
             * @default 0
             */
            failures: number;
            /** Included */
            included: number;
            /**
             * Live
             * @default false
             */
            live: boolean;
            /** Mean Reward */
            mean_reward?: number | null;
            metadata?: components["schemas"]["EvaluationMetadata"] | null;
            /** Next Cursor */
            next_cursor?: string | null;
            /**
             * Pass Scored
             * @default 0
             */
            pass_scored: number;
            /**
             * Passed
             * @default 0
             */
            passed: number;
            performance?: components["schemas"]["EvaluationPerformance"];
            /** Scanned */
            scanned: number;
            /**
             * Scored
             * @default 0
             */
            scored: number;
            /**
             * Slices
             * @default []
             */
            slices: components["schemas"]["EvaluationSlice"][];
            /**
             * State
             * @enum {string}
             */
            state: "complete" | "partial" | "unavailable";
            /** Success Rate */
            success_rate?: number | null;
            /**
             * Traces
             * @default []
             */
            traces: components["schemas"]["TraceSummary"][];
            /**
             * Truncated
             * @default 0
             */
            truncated: number;
        };
        /** @enum {string} */
        TraceOutcome: "pass" | "review" | "scored" | "error" | "truncated" | "unknown";
        /** TraceSummary */
        TraceSummary: {
            /** Completion Tokens */
            completion_tokens?: number | null;
            /** Error */
            error?: string | null;
            /** External Id */
            external_id: string;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Metrics */
            metrics?: {
                [key: string]: number;
            };
            /** Model Calls */
            model_calls?: number | null;
            /** Native Metrics */
            native_metrics?: {
                [key: string]: number;
            };
            /** @default unknown */
            outcome: components["schemas"]["TraceOutcome"];
            /** Prompt Preview */
            prompt_preview?: string | null;
            /** Response Chars */
            response_chars?: number | null;
            /** Response Tokens */
            response_tokens?: number | null;
            /** Reward */
            reward?: number | null;
            /** Reward Components */
            reward_components?: {
                [key: string]: number;
            };
            /** Success */
            success?: boolean | null;
            /** Task */
            task?: string | null;
            /** Task Label */
            task_label?: string | null;
            task_metadata?: components["schemas"]["TaskSliceMetadata"] | null;
            /** Thinking Chars */
            thinking_chars?: number | null;
            /** Thinking Tokens */
            thinking_tokens?: number | null;
            /** Tokens */
            tokens?: number | null;
            /** Tool Calls */
            tool_calls?: number | null;
            /** Trace Type */
            trace_type: string;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /**
         * TraceSummaryPage
         * @description One bounded page of trace summaries for interactive investigation.
         */
        TraceSummaryPage: {
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["TraceSummary"][];
            /**
             * Live
             * @default false
             */
            live: boolean;
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total */
            total: number;
        };
        /** TrackingCapabilities */
        TrackingCapabilities: {
            /**
             * Artifact Lineage
             * @default true
             */
            artifact_lineage: boolean;
            /**
             * Artifacts
             * @default true
             */
            artifacts: boolean;
            /**
             * Live Metrics
             * @default true
             */
            live_metrics: boolean;
            /**
             * Live Traces
             * @default false
             */
            live_traces: boolean;
            /** Provider */
            provider: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** @enum {string} */
        ViewMode: "auto" | "job" | "generic";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    export_api_v1_exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_kinds_api_v1_job_kinds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    job_kind_api_v1_job_kinds__job_kind__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_api_v1_runs_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                work_package_id?: string | null;
                job_kind?: string[];
                status?: string[];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_api_v1_runs_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    locate_run_api_v1_runs_locate_get: {
        parameters: {
            query: {
                run_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alerts_api_v1_runs__run_key__alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    comparison_key_api_v1_runs__run_key__comparison_key_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delta_api_v1_runs__run_key__delta_get: {
        parameters: {
            query?: {
                cursor?: string | null;
            };
            header?: never;
            path: {
                run_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metric_series_api_v1_runs__run_key__metric_series_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetricSeriesQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_api_v1_runs__run_key__metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    semantic_summary_api_v1_runs__run_key__semantic_summary_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SemanticSummaryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_metrics_api_v1_runs__run_key__system_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trace_summaries_api_v1_runs__run_key__traces_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                run_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceSummaryPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    traces_evaluation_api_v1_runs__run_key__traces_evaluation_get: {
        parameters: {
            query?: {
                include_traces?: boolean;
            };
            header?: never;
            path: {
                run_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceEvaluationView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trace_detail_api_v1_runs__run_key__traces__trace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_key: string;
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_view_api_v1_runs__run_key__view_get: {
        parameters: {
            query?: {
                mode?: "auto" | "job" | "generic";
                metric?: string[];
            };
            header?: never;
            path: {
                run_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunViewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serving_capacity_work_package_api_v1_serving_capacity_work_packages__work_package_id__get: {
        parameters: {
            query?: {
                project_id?: string | null;
                source_id?: string | null;
            };
            header?: never;
            path: {
                work_package_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_api_v1_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    refresh_sources_api_v1_sources_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRefreshStatus"];
                };
            };
        };
    };
    work_package_api_v1_work_packages__work_package_id__get: {
        parameters: {
            query?: {
                project_id?: string | null;
                source_id?: string | null;
            };
            header?: never;
            path: {
                work_package_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
