"""Provider-neutral detached execution lifecycle."""

from .admission import (
    AdmissionEntry,
    AdmissionResult,
    AdmissionState,
    ExecutionAdmissionService,
    Placement,
    ProjectControlLocator,
)
from .bundles import (
    ExecutionBundlePlan,
    build_bundle,
    build_execution_bundle,
    plan_execution_bundle,
    verify_bundle,
)
from .cleanup import (
    CleanupEvidenceState,
    ExecutionCleanupReceipt,
    WorkspaceCleanupDisposition,
    cleanup_execution,
)
from .contracts import (
    EXECUTION_LAUNCH_ENVIRONMENT,
    BundleRef,
    ExecutionHandle,
    ExecutionMount,
    ExecutionPlan,
    ExecutionPolicy,
    ExecutionProvider,
    ExecutionRecord,
    ExecutionRequest,
    ExecutionResult,
    ExecutionState,
    LogCursor,
    LogPage,
    ProviderCleanupDeferred,
    ProviderCleanupDisposition,
    ProviderCleanupResult,
    RuntimeImageRef,
)
from .job_package import (
    JOB_PACKAGE_MANIFEST_PATH,
    JOB_PACKAGE_WORKER_COMMAND,
    BackendRuntimeLock,
    DatasetPackageLock,
    EnvironmentActivationLock,
    EnvironmentPackageLock,
    JobPackageManifest,
    RuntimeDependencyLock,
    StagedResourceLock,
)
from .job_package_diff import (
    ChangeKind,
    FieldChange,
    compare_job_packages,
    unchanged_fields,
)
from .lifecycle import wait_for_terminal
from .local_purge import LocalStatePurgeExecutor
from .manifest import (
    BUNDLE_MANIFEST_PATH,
    JOB_MANIFEST_PATH,
    WORKER_COMMAND,
    WORKER_MANIFEST_PATH,
    ExecutionJobManifest,
    ManifestMount,
    resolved_inputs_digest,
)
from .provider_purge import ExecutionProviderPurgeExecutor
from .provider_source import ExecutionProviderSource
from .purge import (
    PurgeAction,
    PurgeActionDeferred,
    PurgeActionExecutor,
    PurgeApplyDeferred,
    PurgeApplyError,
    PurgeMode,
    PurgePlan,
    PurgePlane,
    PurgeReceipt,
    PurgeStore,
    apply_purge_plan,
)
from .purge_planner import (
    PurgeRunCandidate,
    PurgeRunCatalog,
    build_project_purge_plan,
    build_run_purge_plan,
)
from .receipts import ExecutionJournal, latest_runtime_image
from .reconciliation import (
    ExecutionReconciliation,
    ReconciledArtifact,
    ReconciledOutcome,
    ReconciliationState,
    reconcile_execution,
    save_reconciliation,
)
from .recovery import (
    CancelledTrackingWriter,
    TerminalTrackingRecovery,
    TerminalTrackingRecoveryDisposition,
    TerminalTrackingWriter,
    TrackingCancellationRecovery,
    TrackingRecoveryDisposition,
    recover_cancelled_tracking,
    recover_terminal_tracking,
    save_tracking_recovery,
)
from .registry import (
    RegistryLifecycleAdmin,
    RegistryManifestDeletePlan,
    RegistryManifestDeleteReceipt,
    RegistryManifestRef,
)
from .service import (
    ExecutionEvidenceSource,
    ExecutionSubmission,
    ExecutionSubmissionStore,
    JobExecutionService,
)

__all__ = [
    "BUNDLE_MANIFEST_PATH",
    "BackendRuntimeLock",
    "AdmissionEntry",
    "AdmissionResult",
    "AdmissionState",
    "BundleRef",
    "EXECUTION_LAUNCH_ENVIRONMENT",
    "CleanupEvidenceState",
    "CancelledTrackingWriter",
    "ExecutionHandle",
    "ExecutionAdmissionService",
    "Placement",
    "ProjectControlLocator",
    "ExecutionBundlePlan",
    "ExecutionCleanupReceipt",
    "ExecutionMount",
    "ExecutionJournal",
    "ExecutionJobManifest",
    "latest_runtime_image",
    "ExecutionPlan",
    "ExecutionPolicy",
    "ExecutionProvider",
    "ExecutionProviderSource",
    "ExecutionProviderPurgeExecutor",
    "ExecutionRecord",
    "ExecutionReconciliation",
    "ExecutionRequest",
    "ExecutionResult",
    "ExecutionEvidenceSource",
    "ExecutionSubmission",
    "ExecutionSubmissionStore",
    "ExecutionState",
    "LogCursor",
    "LogPage",
    "LocalStatePurgeExecutor",
    "JobExecutionService",
    "JOB_PACKAGE_MANIFEST_PATH",
    "JOB_PACKAGE_WORKER_COMMAND",
    "JobPackageManifest",
    "RuntimeDependencyLock",
    "StagedResourceLock",
    "EnvironmentActivationLock",
    "EnvironmentPackageLock",
    "DatasetPackageLock",
    "JOB_MANIFEST_PATH",
    "WORKER_COMMAND",
    "WORKER_MANIFEST_PATH",
    "ManifestMount",
    "resolved_inputs_digest",
    "ChangeKind",
    "FieldChange",
    "RuntimeImageRef",
    "RegistryLifecycleAdmin",
    "RegistryManifestDeletePlan",
    "RegistryManifestDeleteReceipt",
    "RegistryManifestRef",
    "PurgeRunCandidate",
    "PurgeRunCatalog",
    "build_run_purge_plan",
    "build_project_purge_plan",
    "compare_job_packages",
    "unchanged_fields",
    "TrackingCancellationRecovery",
    "TrackingRecoveryDisposition",
    "TerminalTrackingRecovery",
    "TerminalTrackingRecoveryDisposition",
    "TerminalTrackingWriter",
    "ProviderCleanupDisposition",
    "ProviderCleanupDeferred",
    "ProviderCleanupResult",
    "PurgeAction",
    "PurgeActionDeferred",
    "PurgeActionExecutor",
    "PurgeApplyDeferred",
    "PurgeApplyError",
    "PurgeMode",
    "PurgePlan",
    "PurgePlane",
    "PurgeReceipt",
    "PurgeStore",
    "apply_purge_plan",
    "ReconciledArtifact",
    "ReconciledOutcome",
    "ReconciliationState",
    "WorkspaceCleanupDisposition",
    "build_bundle",
    "build_execution_bundle",
    "cleanup_execution",
    "plan_execution_bundle",
    "reconcile_execution",
    "recover_cancelled_tracking",
    "recover_terminal_tracking",
    "save_reconciliation",
    "save_tracking_recovery",
    "verify_bundle",
    "wait_for_terminal",
]
