"""Reusable, observer-neutral post-training operations."""

from .api import DPOBackend, GRPOBackend, SFTBackend, dpo, grpo, sft
from .data import (
    CompletedRollout,
    PreferenceDataset,
    PreferenceExample,
    RolloutDataset,
    RolloutExample,
    RolloutScore,
    SupervisedDataset,
    SupervisedExample,
)
from .profiles import (
    LFM25_DPO_SMOKE,
    LFM25_RENDERER,
    LFM25_SFT_SMOKE,
    QWEN35_DPO_SMOKE,
    QWEN35_GRPO_MTP_SMOKE,
    QWEN35_GRPO_SMOKE,
    QWEN35_RENDERER,
    QWEN35_SFT_SMOKE,
    TRANSFORMERS_GRPO_ROLLOUT,
    DPOProfile,
    GRPOProfile,
    GRPORolloutProfile,
    QLoRAProfile,
    RendererProfile,
    SFTProfile,
    TrainingLoop,
)
from .rendering import RenderedPreferenceExample, RenderedSFTExample, render_preferences, render_supervised
from .requests import DPORequest, GRPORequest, OnlineRLEnvironment, SFTRequest
from .results import TrainingResult, TrainingSummary

__all__ = [
    "CompletedRollout",
    "DPOBackend",
    "DPOProfile",
    "DPORequest",
    "GRPOBackend",
    "GRPOProfile",
    "GRPORequest",
    "GRPORolloutProfile",
    "LFM25_DPO_SMOKE",
    "LFM25_RENDERER",
    "LFM25_SFT_SMOKE",
    "PreferenceDataset",
    "PreferenceExample",
    "QLoRAProfile",
    "QWEN35_DPO_SMOKE",
    "QWEN35_GRPO_MTP_SMOKE",
    "QWEN35_GRPO_SMOKE",
    "QWEN35_RENDERER",
    "QWEN35_SFT_SMOKE",
    "RenderedPreferenceExample",
    "RenderedSFTExample",
    "RendererProfile",
    "OnlineRLEnvironment",
    "RolloutDataset",
    "RolloutExample",
    "RolloutScore",
    "SFTBackend",
    "SFTProfile",
    "SFTRequest",
    "SupervisedDataset",
    "SupervisedExample",
    "TrainingLoop",
    "TRANSFORMERS_GRPO_ROLLOUT",
    "TrainingResult",
    "TrainingSummary",
    "dpo",
    "grpo",
    "render_preferences",
    "render_supervised",
    "sft",
]
