"""Backend-neutral exact-token contracts for on-policy distillation."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Protocol

from .online_rl import EnvironmentRollout, PolicyGenerator, RolloutBatch


@dataclass(frozen=True, slots=True)
class DistillationBatch:
    """Fresh environment rollouts produced by one exact student revision."""

    batch_id: str
    policy_revision: str
    step: int
    rollouts: tuple[EnvironmentRollout, ...]

    def __post_init__(self) -> None:
        if not self.batch_id.strip() or not self.policy_revision.strip():
            raise ValueError("distillation batches require batch and policy revision identities")
        if self.step < 0 or not self.rollouts:
            raise ValueError("distillation batches require a non-negative step and fresh rollouts")
        trace_ids = tuple(rollout.trace.external_id for rollout in self.rollouts)
        if len(trace_ids) != len(set(trace_ids)):
            raise ValueError(f"distillation batch {self.batch_id!r} contains duplicate rollout identities")


class DistillationBatchSource(Protocol):
    async def generate(self, batch: RolloutBatch, generator: PolicyGenerator) -> DistillationBatch: ...


@dataclass(slots=True)
class DistillationBatchLedger:
    """Process-local consume-once guard for fresh distillation batches."""

    policy_revision: str
    _consumed: set[str] = field(default_factory=set, init=False, repr=False)

    def consume(self, batch: DistillationBatch) -> tuple[EnvironmentRollout, ...]:
        if batch.policy_revision != self.policy_revision:
            raise ValueError(
                f"distillation batch {batch.batch_id!r} was generated by policy revision "
                f"{batch.policy_revision!r}, expected {self.policy_revision!r}"
            )
        if batch.batch_id in self._consumed:
            raise ValueError(f"distillation batch {batch.batch_id!r} has already been consumed")
        self._consumed.add(batch.batch_id)
        return batch.rollouts


__all__ = ["DistillationBatch", "DistillationBatchLedger", "DistillationBatchSource"]
