"""Recipe and work-package composition independent of any concrete host."""

from .contracts import (
    JobDefinition,
    JobKind,
    JobOperation,
    JobStatus,
    Recipe,
    RecipeJob,
    ResolvedSeats,
    SeatBinding,
    Stage,
    WorkPackage,
    WorkPackageJobResult,
    WorkPackageResult,
    WorkPackageSchema,
    load_work_package,
)
from .execution import (
    ArtifactInput,
    ArtifactMaterializer,
    RunOperation,
    RunSpec,
    execute_run,
    execute_run_tracked,
)
from .project_brief import (
    ProjectBrief,
    ServingRequirements,
    load_project_brief,
    project_brief_digest,
    project_brief_snapshot,
)
from .runner import (
    ResolvedSeat,
    ResolvedWorkPackage,
    RunExecutor,
    SeatResolver,
    WorkPackageContext,
    WorkPackageHostFactory,
    WorkPackageHostRequest,
    resolve_work_package,
    run_work_package,
    run_work_package_job,
    validate_work_package,
)

JobRuntime = WorkPackageContext
ProjectExecutionRequest = WorkPackageHostRequest
ProjectEntry = WorkPackageHostFactory

__all__ = [
    "ArtifactInput",
    "ArtifactMaterializer",
    "JobDefinition",
    "JobKind",
    "JobRuntime",
    "JobOperation",
    "JobStatus",
    "Recipe",
    "RecipeJob",
    "ProjectEntry",
    "ProjectBrief",
    "ProjectExecutionRequest",
    "ResolvedSeat",
    "ResolvedSeats",
    "ResolvedWorkPackage",
    "RunExecutor",
    "RunOperation",
    "RunSpec",
    "SeatResolver",
    "ServingRequirements",
    "SeatBinding",
    "Stage",
    "WorkPackage",
    "WorkPackageContext",
    "WorkPackageHostFactory",
    "WorkPackageHostRequest",
    "WorkPackageJobResult",
    "WorkPackageResult",
    "WorkPackageSchema",
    "execute_run",
    "execute_run_tracked",
    "load_work_package",
    "load_project_brief",
    "project_brief_digest",
    "project_brief_snapshot",
    "resolve_work_package",
    "run_work_package",
    "run_work_package_job",
    "validate_work_package",
]
