"""Recipe and work-package composition independent of any concrete host."""

from .contracts import (
    JobDefinition,
    JobKind,
    JobOperation,
    JobStatus,
    Recipe,
    RecipeJob,
    ResolvedSeats,
    SeatBinding,
    Stage,
    WorkPackage,
    WorkPackageJobResult,
    WorkPackageResult,
    WorkPackageSchema,
    load_work_package,
)
from .execution import (
    ArtifactInput,
    ArtifactMaterializer,
    RunOperation,
    RunSpec,
    execute_run,
    execute_run_tracked,
)
from .runner import (
    ResolvedSeat,
    ResolvedWorkPackage,
    RunExecutor,
    WorkPackageContext,
    resolve_work_package,
    run_work_package,
    validate_work_package,
)

__all__ = [
    "ArtifactInput",
    "ArtifactMaterializer",
    "JobDefinition",
    "JobKind",
    "JobOperation",
    "JobStatus",
    "Recipe",
    "RecipeJob",
    "ResolvedSeat",
    "ResolvedSeats",
    "ResolvedWorkPackage",
    "RunExecutor",
    "RunOperation",
    "RunSpec",
    "SeatBinding",
    "Stage",
    "WorkPackage",
    "WorkPackageContext",
    "WorkPackageJobResult",
    "WorkPackageResult",
    "WorkPackageSchema",
    "execute_run",
    "execute_run_tracked",
    "load_work_package",
    "resolve_work_package",
    "run_work_package",
    "validate_work_package",
]
