import React, {useState} from "react";
const signed=n=>`${n>0?"+":""}${n.toFixed(3)}`;
function Credit({value}) { return <span className={`strategy-credit ${value<0?"negative":"positive"}`}>{signed(value)}</span>; }
export function StrategyVisual({title,views,body}) {
 const [weight,setWeight]=useState(1);
 const [lengthPower,setLengthPower]=useState(0);
 if(!views) return null;
 const vendor=views.vendor, ads=views.ads, bad=vendor.turns[3];
 if(title.startsWith("Reward shaping")) {
  const rows=vendor.siblings;
  const adjusted=rows.map(r=>r.native_reward-(r.guard_violation?1.125:0));
  const mean=adjusted.reduce((a,b)=>a+b,0)/rows.length;
  return <figure className="strategy-explainer"><figcaption>Episode penalty · six recorded vendor-payment siblings</figcaption><div className="strategy-data-table"><table><thead><tr><th>Sibling</th><th>Guard broken?</th><th>Native reward</th><th>After cost 1.125</th><th>Credit before</th><th>Credit after</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i} className={r.selected?"selected-evidence":""}><th>Attempt {i+1}{r.selected?" · focal trace":""}</th><td>{r.guard_violation?"Yes":"No"}</td><td>{r.native_reward.toFixed(3)}</td><td>{adjusted[i].toFixed(3)}</td><td><Credit value={r.episode_credit}/></td><td><Credit value={adjusted[i]-mean}/></td></tr>)}</tbody></table></div><p>Cost changes the episode score; sibling centering determines the credit. A shared penalty cancels when every sibling breaks a guard.</p><small>Counterfactual labels for this actual group, before common positive rescaling. Not a training outcome or an action-level mask.</small></figure>;
 }
 if(title.startsWith("Increasing turn")) return <figure className="strategy-explainer"><figcaption>Turn weight · the same prohibited email on Turn 3</figcaption><div className="sampo-control"><label htmlFor="turn-weight-demo">Local turn weight</label><select id="turn-weight-demo" value={weight} onChange={e=>setWeight(Number(e.target.value))}>{[0,1,2,4].map(w=><option key={w} value={w}>{w}</option>)}</select></div><div className="credit-calculation"><div><small>Episode credit</small><Credit value={vendor.episode_credit}/></div><div><small>Local credit × {weight}</small><Credit value={bad.turn_advantage*weight}/></div><div><small>Combined credit</small><Credit value={vendor.episode_credit+bad.turn_advantage*weight}/></div></div><p>Turn 3 has one observed member at its anchor. Its local relative credit is zero, so raising the weight leaves the positive episode label in place.</p><small>Current-recipe arithmetic on retained tokens. This does not reconstruct the historical optimizer gradient.</small></figure>;
 if(title.startsWith("VORTEX")) {
  const rows=body.split("\n").filter(l=>/^\| (uniform|current_defaults|no_uncertainty_bonus|more_exploration) \|/.test(l)).map(l=>l.split("|").slice(1,-1).map(c=>c.trim()));
  const labels={uniform:"Uniform",current_defaults:"Current VORTEX",no_uncertainty_bonus:"No uncertainty bonus",more_exploration:"50% exploration"};
  return <><figure className="strategy-explainer"><figcaption>Sampling strategy · fixed FP16 base-100 later outcome bank</figcaption><div className="allocator-heading"><span>Allocator</span><span>Useful groups</span><span>Tasks covered / 114</span></div>{rows.map(r=><div className="allocator-row" key={r[0]}><b>{labels[r[0]]}</b><label><meter min="0" max="100" value={parseFloat(r[1])}/><span>{r[1]}</span></label><label><meter min="0" max="114" value={parseFloat(r[2])}/><span>{r[2]} / 114</span></label></div>)}<p>More usable groups can come with fewer tasks covered. These bars show allocation on frozen outcomes; they cannot show what a changed policy would learn.</p></figure><figure className="strategy-explainer"><figcaption>Practice queue · triggered by a rare complete branch</figcaption><ol className="practice-stages"><li><b>Recorded: complete solution</b><span>Advertising, step 26 · 1 successful sibling, 5 failed siblings.</span></li><li><b>Required gate: optimizer use</b><span>Verify that the complete trajectory entered an update. Its historical admission is unresolved.</span></li><li><b>Proposed: bounded fresh rechecks</b><span>Revisit the task in later populations; collect new trajectories and keep within-population task uniqueness.</span></li><li><b>Measure: repeatability</b><span>Track complete branches and guard violations at fixed checkpoints; expire the queue by declared criteria.</span></li></ol><small>The successful branch is recorded; the queue and its learning effect are proposed. A stored success is not a guarantee of reinforcement.</small></figure></>;
 }
 if(title.startsWith("Length compensation")) {
  const short=vendor.turns.reduce((s,t)=>s+t.token_count,0), long=ads.turns.reduce((s,t)=>s+t.token_count,0), ratio=long/short;
  const tokenFactor=Math.pow(ratio,lengthPower-1), episodeFactor=Math.pow(ratio,lengthPower);
  return <figure className="strategy-explainer"><figcaption>Length weighting · two actual sampled-token masks</figcaption><div className="sampo-control"><label htmlFor="length-demo">Weighting rule</label><select id="length-demo" value={lengthPower} onChange={e=>setLengthPower(Number(e.target.value))}><option value="0">Current · equal episode weight</option><option value="0.5">Square root of length</option><option value="1">Linear in length</option></select></div><div className="length-row"><b>Vendor payment · {short.toLocaleString()} tokens</b><meter min="0" max="1" value="1"/><span>Per-token factor 1.00</span></div><div className="length-row"><b>Advertising · {long.toLocaleString()} tokens</b><meter min="0" max="1" value={tokenFactor}/><span>Per-token factor {tokenFactor.toFixed(2)}</span></div><p>The long episode's total weight is {episodeFactor.toFixed(2)}× the vendor episode's weight under this rule. Increasing per-token influence also increases the long episode's total influence.</p><small>Controlled illustration: equal advantage, equal importance weights, corrected unclipped loss, same batch denominator. Actual token counts; not measured parameter gradients or a percentile comparison.</small></figure>;
 }
 if(title.startsWith("Candidate system")) return <figure className="strategy-explainer"><figcaption>Candidate system · separate fixes, separate tests</figcaption><ol className="practice-stages"><li><b>Correct delivery</b><span>Preserve supplied turn credit at its own sampled tokens.</span></li><li><b>Correct the harmful label</b><span>Use evidence-backed negative cost on its declared turn mask; retain ordinary credit outside it.</span></li><li><b>Keep sampling feedback valid</b><span>Separate signed training costs from VORTEX's bounded feedback.</span></li><li><b>Test repeated success</b><span>Measure the corrected loss, then local costs, then bounded practice in separate comparisons.</span></li></ol><small>This is the proposed causal test sequence, not a validated new training system.</small></figure>;
 return null;
}
